# Generated by Django 5.1.2 on 2025-03-06 17:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FireReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('روزکار اول', 'روزکار اول'), ('روزکار دوم', 'روزکار دوم'), ('عصرکار اول', 'عصرکار اول'), ('عصرکار دوم', 'عصرکار دوم'), ('شب کار اول', 'شب کار اول'), ('شب کار دوم', 'شب کار دوم'), ('OFF اول', 'OFF اول'), ('OFF دوم', 'OFF دوم')], max_length=20, verbose_name='شیفت کاری')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت گزارش')),
                ('horn_status', models.CharField(choices=[('normal', 'نرمال'), ('warning', 'هشدار'), ('critical', 'بحرانی')], max_length=10, verbose_name='وضعیت بوق و چراغ گردان')),
                ('hose_status', models.CharField(choices=[('normal', 'نرمال'), ('warning', 'هشدار'), ('critical', 'بحرانی')], max_length=10, verbose_name='وضعیت شیلنگ\u200cها و اتصالات')),
                ('monitor_status', models.CharField(choices=[('normal', 'نرمال'), ('warning', 'هشدار'), ('critical', 'بحرانی')], max_length=10, verbose_name='وضعیت مانیتور')),
                ('extinguisher_status', models.CharField(choices=[('normal', 'نرمال'), ('warning', 'هشدار'), ('critical', 'بحرانی')], max_length=10, verbose_name='وضعیت خاموش\u200cکننده\u200cهای دستی')),
                ('equipment_status', models.CharField(choices=[('normal', 'نرمال'), ('warning', 'هشدار'), ('critical', 'بحرانی')], max_length=10, verbose_name='وضعیت تجهیزات آتش\u200cنشانی')),
                ('foam_status', models.CharField(choices=[('normal', 'نرمال'), ('warning', 'هشدار'), ('critical', 'بحرانی')], max_length=10, verbose_name='وضعیت پودر و فوم خودرو')),
                ('water_status', models.CharField(choices=[('normal', 'نرمال'), ('warning', 'هشدار'), ('critical', 'بحرانی')], max_length=10, verbose_name='وضعیت آب')),
                ('tire_status', models.CharField(choices=[('normal', 'نرمال'), ('warning', 'هشدار'), ('critical', 'بحرانی')], max_length=10, verbose_name='وضعیت لاستیک\u200cها')),
                ('brake_status', models.CharField(choices=[('normal', 'نرمال'), ('warning', 'هشدار'), ('critical', 'بحرانی')], max_length=10, verbose_name='وضعیت سیستم ترمز خودرو')),
                ('lighting_status', models.CharField(choices=[('normal', 'نرمال'), ('warning', 'هشدار'), ('critical', 'بحرانی')], max_length=10, verbose_name='وضعیت سیستم روشنایی')),
                ('incident_dispatch_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد اعزام به محل حادثه')),
                ('personal_incident_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد حوادث فردی')),
                ('equipment_incident_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد حوادث تجهیزاتی')),
                ('fire_incident_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد حوادث آتش\u200cسوزی')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('firefighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_firefighter', to=settings.AUTH_USER_MODEL, verbose_name='آتش\u200cنشان')),
                ('shift_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_shift_operator', to=settings.AUTH_USER_MODEL, verbose_name='متصدی شیفت آتش\u200cنشانی')),
            ],
            options={
                'verbose_name': 'گزارش آتش\u200cنشانی',
                'verbose_name_plural': 'گزارشات آتش\u200cنشانی',
                'ordering': ['-report_date'],
            },
        ),
    ]
