# Generated by Django 5.1.2 on 2025-03-06 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='firereport',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت تأیید'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fire_reports', to=settings.AUTH_USER_MODEL, verbose_name='تأیید شده توسط'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد'),
        ),
    ]
