# Generated by Django 5.1.2 on 2025-03-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_reports', '0002_firereport_approval_date_firereport_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firereport',
            name='brake_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت سیستم ترمز خودرو'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='equipment_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت تجهیزات آتش\u200cنشانی'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='extinguisher_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت خاموش\u200cکننده\u200cهای دستی'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='foam_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت پودر و فوم خودرو'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='horn_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت بوق و چراغ گردان'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='hose_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت شیلنگ\u200cها و اتصالات'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='lighting_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت سیستم روشنایی'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='monitor_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت مانیتور'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='tire_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت لاستیک\u200cها'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='water_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت آب'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='brake_status',
            field=models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت سیستم ترمز خودرو'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='equipment_status',
            field=models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت تجهیزات آتش\u200cنشانی'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='extinguisher_status',
            field=models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت خاموش\u200cکننده\u200cهای دستی'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='foam_status',
            field=models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت پودر و فوم خودرو'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='horn_status',
            field=models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت بوق و چراغ گردان'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='hose_status',
            field=models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت شیلنگ\u200cها و اتصالات'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='lighting_status',
            field=models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت سیستم روشنایی'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='monitor_status',
            field=models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت مانیتور'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='tire_status',
            field=models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت لاستیک\u200cها'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='water_status',
            field=models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت آب'),
        ),
    ]
