# Generated by Django 5.1.2 on 2025-03-07 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0012_emergencyvehicle'),
        ('contractor_management', '0008_alter_report_unique_together'),
        ('fire_reports', '0003_firereport_brake_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firereport',
            name='company_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.emergencyvehicle', verbose_name='خودروی امدادی شرکت'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='contractor_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractor_management.vehicle', verbose_name='خودروی پیمانکار'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='vehicle_source',
            field=models.CharField(choices=[('company', 'خودروی شرکت'), ('contractor', 'خودروی پیمانکار')], default=1, max_length=20, verbose_name='منبع خودرو'),
            preserve_default=False,
        ),
    ]
