# Generated by Django 5.1.2 on 2025-03-07 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0012_emergencyvehicle'),
        ('contractor_management', '0008_alter_report_unique_together'),
        ('fire_reports', '0004_firereport_company_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_source', models.CharField(choices=[('company', 'خودروی شرکت'), ('contractor', 'خودروی پیمانکار')], max_length=20, verbose_name='منبع خودرو')),
                ('horn_status', models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت بوق و چراغ گردان')),
                ('horn_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت بوق و چراغ گردان')),
                ('hose_status', models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت شیلنگ\u200cها و اتصالات')),
                ('hose_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت شیلنگ\u200cها و اتصالات')),
                ('monitor_status', models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت مانیتور')),
                ('monitor_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت مانیتور')),
                ('extinguisher_status', models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت خاموش\u200cکننده\u200cهای دستی')),
                ('extinguisher_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت خاموش\u200cکننده\u200cهای دستی')),
                ('equipment_status', models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت تجهیزات آتش\u200cنشانی')),
                ('equipment_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت تجهیزات آتش\u200cنشانی')),
                ('foam_status', models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت پودر و فوم خودرو')),
                ('foam_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت پودر و فوم خودرو')),
                ('water_status', models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت آب')),
                ('water_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت آب')),
                ('tire_status', models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت لاستیک\u200cها')),
                ('tire_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت لاستیک\u200cها')),
                ('brake_status', models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت سیستم ترمز خودرو')),
                ('brake_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت سیستم ترمز خودرو')),
                ('lighting_status', models.CharField(choices=[('suitable', 'مناسب'), ('unsuitable', 'نامناسب')], max_length=10, verbose_name='وضعیت سیستم روشنایی')),
                ('lighting_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت سیستم روشنایی')),
                ('company_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.emergencyvehicle', verbose_name='خودروی امدادی شرکت')),
                ('contractor_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractor_management.vehicle', verbose_name='خودروی پیمانکار')),
                ('fire_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_reports', to='fire_reports.firereport', verbose_name='گزارش آتش\u200cنشانی')),
            ],
            options={
                'verbose_name': 'گزارش وضعیت خودرو',
                'verbose_name_plural': 'گزارشات وضعیت خودرو',
            },
        ),
    ]
