# Generated by Django 5.2.4 on 2025-11-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_reports', '0005_vehiclestatusreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleStatusReport',
        ),
    ]
