# Generated by Django 4.2 on 2025-12-05 16:23

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('google', 'Google AI Studio (Gemini)'), ('local', 'Local API (Ollama)')], default='openai', max_length=20, verbose_name='ارائه\u200cدهنده AI')),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='کلید API (به صورت رمزگذاری\u200cشده ذخیره می\u200cشود)', max_length=500, null=True, verbose_name='API Key'))),
                ('api_base_url', models.CharField(blank=True, help_text='برای Google AI Studio: https://generativelanguage.googleapis.com/v1beta', max_length=500, null=True, verbose_name='آدرس پایه API')),
                ('model', models.CharField(default='gpt-4', help_text='نام مدل استفاده شده (مثلاً: gpt-4, gemini-pro, claude-3-opus)', max_length=100, verbose_name='مدل')),
                ('timeout', models.IntegerField(default=30, help_text='حداکثر زمان انتظار برای پاسخ API', verbose_name='Timeout (ثانیه)')),
                ('max_retries', models.IntegerField(default=3, help_text='تعداد دفعات تلاش مجدد در صورت خطا', verbose_name='تعداد تلاش مجدد')),
                ('cache_timeout', models.IntegerField(default=3600, help_text='زمان نگهداری نتایج در کش (1 ساعت = 3600 ثانیه)', verbose_name='زمان کش (ثانیه)')),
                ('temperature', models.FloatField(default=0.7, help_text='میزان خلاقیت پاسخ\u200cها (0-1)', verbose_name='Temperature')),
                ('is_active', models.BooleanField(default=True, help_text='آیا سرویس AI فعال است؟', verbose_name='فعال')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تست اتصال')),
                ('last_test_status', models.BooleanField(blank=True, help_text='True = موفق، False = ناموفق', null=True, verbose_name='وضعیت آخرین تست')),
                ('last_test_message', models.TextField(blank=True, null=True, verbose_name='پیام آخرین تست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات AI',
                'verbose_name_plural': 'تنظیمات AI',
            },
        ),
    ]
