"""
Django settings for HSCprojects project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from logging.handlers import TimedRotatingFileHandler
from datetime import datetime
from django.conf.locale.fa import formats as fa_formats



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ygf6#b*bj-ko2fimc)sg=u2vo6c)5a1#c5#zr=@#8&o7nd*tpt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', 

    # Third-party apps
    'corsheaders',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_jalali',
    'jalali_date', # شما هم django_jalali و هم jalali_date را دارید؟ معمولا یکی کافیست.
    'django_select2',
    'import_export',
    'formtools',
    'rest_framework',

    # Celery related apps
    'django_celery_results',   # برای ذخیره نتایج تسک‌ها (فقط یک بار)
    'django_celery_beat',    # <<<--- برای زمان‌بندی تسک‌ها (اضافه شد)

    # Your project apps (use Config class where defined)
    'permissions.apps.PermissionsConfig',
    'meetings.apps.MeetingsConfig',
    "dashboard.apps.DashboardConfig",
    "accounts.apps.AccountsConfig",
    "anomalis.apps.AnomalisConfig",
    'analytics.apps.AnalyticsConfig',
    'shift_manager.apps.ShiftManagerConfig',
    'BaseInfo.apps.BaseinfoConfig',
    'OperationsShiftReports.apps.OperationsshiftreportsConfig',
    'dailyreport_hse.apps.DailyreportHseConfig',
    'leave_reports.apps.LeaveReportsConfig',
    'contractor_management.apps.ContractorManagementConfig',
    'hse_incidents.apps.HseIncidentsConfig',
    'machine_checklist.apps.MachineChecklistConfig',
    'fire_reports.apps.FireReportsConfig',
    'checklist_app.apps.ChecklistAppConfig',  # اضافه کردن اپلیکیشن چک‌لیست
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'HSCprojects.urls'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # مسیرهای اضافی برای تمپلیت‌ها (اختیاری)
        'APP_DIRS': True,  # فعال کردن جستجو در دایرکتوری templates داخل اپ‌ها
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_profile_processor',
                'analytics.context_processors.anomaly_stats_context',
                'dashboard.context_processors.notification_context_processor',
                'shift_manager.context_processors.shift_context_processor',
                'shift_manager.context_processors.shift_data_processor',
                'permissions.context_processors.permission_context',
            ],
            'builtins': [
                'django_jalali.templatetags.jformat',
            ],
        },
    },
]

WSGI_APPLICATION = 'HSCprojects.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#'default': {
#    'ENGINE': 'django.db.backends.postgresql',
#     'NAME': 'hsc_db',
#      'USER': 'hsc_user',
#       'PASSWORD': 'Znmk@0900',
#        'HOST': 'localhost',
#         'PORT': '5432',
#      }
#   }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,  # افزایش زمان timeout برای عملیات‌های طولانی
            'check_same_thread': False,  # اجازه دسترسی همزمان به پایگاه داده
            'isolation_level': None,  # غیرفعال کردن isolation level برای جلوگیری از قفل شدن
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/dashboard/'


# ارسال پیامک
SMSIR_API_KEY = 'gCLhWKiCoUXwUQiNBIXCpQ81IiGfujNmKgWyrQr19WwgDkv3dSfFSDgIbsSEoo03'
SMSIR_LINE_NUMBER = '30007732001185'




fa_formats.DATETIME_FORMAT = "Y/m/d H:i"
fa_formats.DATE_FORMAT = "Y/m/d"




JALALI_DATE_DEFAULTS = {
    # if change it to true then all dates of the list_display will convert to the Jalali.
    'LIST_DISPLAY_AUTO_CONVERT': False,
    'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            # loading datepicker
            'admin/js/django_jalali.min.js',
            # OR
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/calendar.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js',
            # 'admin/js/main.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',    # برای محیط لوکال (اگر از پورت 8000 استفاده می‌کنید)
    'http://127.0.0.1:8000',  # برای محیط لوکال (اگر از پورت 8000 استفاده می‌کنید)
    'https://miepcoj.ir',       # برای محیط سرور
    'https://www.miepcoj.ir',    # برای محیط سرور
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    # سایر هدرهایی که فرانت‌اند شما استفاده می‌کند
]

# اگر نیاز دارید که مرورگر کوکی‌ها را ارسال کند (مثلاً برای احراز هویت):
CORS_ALLOW_CREDENTIALS = True

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_TIMEZONE = 'Asia/Tehran'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'your-email@gmail.com'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] {levelname} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'debug.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',  # اضافه کردن کدگذاری UTF-8
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',  # تغییر خروجی به stdout
        },
    },
    'loggers': {
        'contractor_management': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
} 