# Generated by Django 5.1.2 on 2025-04-10 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseInfo', '0013_emergencyvehicle_has_brake_and_more'),
        ('anomalis', '0006_comment_file_alter_comment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('machine', 'ماشین'), ('location', 'مکان')], max_length=10, verbose_name='نوع چک لیست')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('shift', models.CharField(max_length=50, verbose_name='شیفت کاری')),
                ('shift_group', models.CharField(max_length=50, verbose_name='گروه شیفت')),
                ('location_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anomalis.locationsection', verbose_name='بخش مکانی')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_checklists', to='BaseInfo.miningmachine', verbose_name='ماشین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_checklists', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'چک لیست',
                'verbose_name_plural': 'چک لیست ها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_scope', models.CharField(choices=[('machine', 'ماشین'), ('location', 'مکان')], max_length=10, verbose_name='محدوده سوال')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('is_required', models.BooleanField(default=True, verbose_name='اجباری')),
                ('question_type', models.CharField(choices=[('text', 'متنی'), ('option', 'گزینه\u200cای')], max_length=10, verbose_name='نوع سوال')),
                ('options', models.TextField(blank=True, null=True, verbose_name='گزینه\u200cها')),
                ('default_anomaly_description_on_fail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anomalis.anomalydescription', verbose_name='شرح آنومالی پیش\u200cفرض در صورت عدم قبول')),
                ('default_priority_on_fail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anomalis.priority', verbose_name='اولویت آنومالی پیش\u200cفرض در صورت عدم قبول')),
                ('location_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anomalis.locationsection', verbose_name='بخش مکانی')),
                ('machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_questions', to='BaseInfo.typemachine', verbose_name='نوع ماشین')),
            ],
            options={
                'verbose_name': 'سوال چک لیست',
                'verbose_name_plural': 'سوالات چک لیست',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='پاسخ متنی')),
                ('selected_option', models.CharField(blank=True, max_length=255, null=True, verbose_name='گزینه انتخاب شده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist_app.checklist', verbose_name='چک لیست')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist_app.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ چک لیست',
                'verbose_name_plural': 'پاسخ های چک لیست',
            },
        ),
    ]
