# Generated by Django 5.1.2 on 2025-04-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0006_comment_file_alter_comment_comment'),
        ('checklist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='default_anomaly_description_on_fail',
        ),
        migrations.AddField(
            model_name='question',
            name='anomaly_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anomalis.anomalytype', verbose_name='نوع آنومالی پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='question',
            name='default_corrective_action',
            field=models.TextField(blank=True, null=True, verbose_name='اقدام اصلاحی پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='question',
            name='hse_type',
            field=models.CharField(blank=True, choices=[('H', 'Health'), ('S', 'Safety'), ('E', 'Environment')], max_length=1, null=True, verbose_name='نوع HSE پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='question',
            name='unacceptable_options',
            field=models.TextField(blank=True, help_text='گزینه\u200cهایی که در صورت انتخاب منجر به ایجاد آنومالی می\u200cشوند (با کاما جدا شوند)', null=True, verbose_name='گزینه\u200cهای غیرقابل قبول'),
        ),
        migrations.AlterField(
            model_name='question',
            name='default_priority_on_fail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anomalis.priority', verbose_name='اولویت آنومالی پیش\u200cفرض'),
        ),
    ]
