# Generated by Django 5.1.2 on 2025-04-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0013_emergencyvehicle_has_brake_and_more'),
        ('checklist_app', '0002_remove_question_default_anomaly_description_on_fail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ\u200cها'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='گزینه انتخاب شده'),
        ),
        migrations.AlterField(
            model_name='question',
            name='machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='BaseInfo.typemachine', verbose_name='نوع ماشین'),
        ),
    ]
