# Generated by Django 5.1.2 on 2025-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0003_alter_answer_options_alter_answer_selected_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default_anomaly_description',
            field=models.TextField(blank=True, help_text='شرح پیش\u200cفرض آنومالی که در صورت پاسخ غیرقابل قبول ایجاد می\u200cشود', null=True, verbose_name='شرح آنومالی پیش\u200cفرض'),
        ),
    ]
