# Generated by Django 5.1.2 on 2025-04-12 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0006_comment_file_alter_comment_comment'),
        ('checklist_app', '0004_question_default_anomaly_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='default_anomaly_description',
            field=models.ForeignKey(blank=True, help_text='شرح پیش\u200cفرض آنومالی که در صورت پاسخ غیرقابل قبول ایجاد می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, to='anomalis.anomalydescription', verbose_name='شرح آنومالی پیش\u200cفرض'),
        ),
    ]
