# Generated by Django 5.1.2 on 2025-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0005_alter_question_default_anomaly_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='shift',
            field=models.CharField(choices=[('day', 'روزکاراول'), ('day2', 'روزکاردوم'), ('evening', 'عصرکاراول'), ('evening2', 'عصرکاردوم'), ('night', 'شبکاراول'), ('night2', 'شبکاردوم')], max_length=50, verbose_name='شیفت کاری'),
        ),
    ]
