# Generated by Django 5.1.2 on 2025-04-20 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0006_alter_checklist_shift'),
        ('contractor_management', '0009_vehicle_vehicle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='contractor_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_checklists', to='contractor_management.vehicle', verbose_name='ماشین\u200cآلات پیمانکار'),
        ),
        migrations.AddField(
            model_name='question',
            name='vehicle_category',
            field=models.CharField(blank=True, choices=[('mining', 'ماشین آلات معدنی'), ('light', 'خودروهای سبک')], max_length=10, null=True, verbose_name='دسته\u200cبندی خودرو'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='checklist_type',
            field=models.CharField(choices=[('machine', 'ماشین'), ('location', 'مکان'), ('contractor_vehicle', 'ماشین\u200cآلات پیمانکار')], max_length=20, verbose_name='نوع چک لیست'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_scope',
            field=models.CharField(choices=[('machine', 'ماشین'), ('location', 'مکان'), ('contractor_vehicle', 'ماشین\u200cآلات پیمانکار')], max_length=20, verbose_name='محدوده سوال'),
        ),
    ]
