# Generated by Django 5.1.2 on 2025-05-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0013_emergencyvehicle_has_brake_and_more'),
        ('anomalis', '0006_comment_file_alter_comment_comment'),
        ('checklist_app', '0007_checklist_contractor_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='location_section',
        ),
        migrations.RemoveField(
            model_name='question',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_scope',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vehicle_category',
        ),
        migrations.AddField(
            model_name='question',
            name='location_sections',
            field=models.ManyToManyField(blank=True, to='anomalis.locationsection', verbose_name='بخش\u200cهای مکانی'),
        ),
        migrations.AddField(
            model_name='question',
            name='machine_types',
            field=models.ManyToManyField(blank=True, related_name='questions', to='BaseInfo.typemachine', verbose_name='انواع ماشین'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_scopes',
            field=models.JSONField(default=list, help_text='لیست محدوده\u200cهایی که این سوال در آن\u200cها نمایش می\u200cشود', verbose_name='محدوده\u200cهای سوال'),
        ),
        migrations.AddField(
            model_name='question',
            name='vehicle_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='دسته\u200cبندی\u200cهای خودرو'),
        ),
    ]
