# Generated by Django 4.2 on 2025-11-30 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseInfo', '0013_emergencyvehicle_has_brake_and_more'),
        ('anomalis', '0006_comment_file_alter_comment_comment'),
        ('contractor_management', '0016_contractor_user_employee_user'),
        ('checklist_app', '0008_remove_question_location_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام برنامه')),
                ('checklist_type', models.CharField(choices=[('machine', 'ماشین'), ('location', 'مکان'), ('contractor_vehicle', 'ماشین\u200cآلات پیمانکار')], max_length=20, verbose_name='نوع چک لیست')),
                ('schedule_type', models.CharField(choices=[('monthly_days', 'روزهای مشخص ماه (مثلاً 1 و 15 هر ماه)'), ('specific_dates', 'تاریخ\u200cهای مشخص'), ('weekly', 'هفتگی')], max_length=20, verbose_name='نوع برنامه\u200cریزی')),
                ('monthly_days', models.JSONField(blank=True, default=list, help_text='لیست روزهای ماه که چک\u200cلیست باید انجام شود (مثلاً [1, 15])', verbose_name='روزهای ماه')),
                ('specific_dates', models.JSONField(blank=True, default=list, help_text='لیست تاریخ\u200cهای مشخص (فرمت: YYYY-MM-DD)', verbose_name='تاریخ\u200cهای مشخص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('target_contractor_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_checklists', to='contractor_management.vehicle', verbose_name='ماشین پیمانکار هدف')),
                ('target_location_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_checklists', to='anomalis.locationsection', verbose_name='بخش مکانی هدف')),
                ('target_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_checklists', to='BaseInfo.miningmachine', verbose_name='ماشین هدف')),
            ],
            options={
                'verbose_name': 'برنامه زمان\u200cبندی چک لیست',
                'verbose_name_plural': 'برنامه\u200cهای زمان\u200cبندی چک لیست',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='machine_status',
            field=models.CharField(blank=True, choices=[('healthy', 'سالم'), ('broken', 'خراب/در حال تعمیر')], help_text='فقط برای چک\u200cلیست\u200cهای ماشین: وضعیت ماشین قبل از شروع چک\u200cلیست', max_length=20, null=True, verbose_name='وضعیت ماشین'),
        ),
        migrations.CreateModel(
            name='ScheduledChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='تاریخ موعد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('skipped', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_scheduled_checklists', to=settings.AUTH_USER_MODEL, verbose_name='تکمیل شده توسط')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='checklist_app.checklistschedule', verbose_name='برنامه زمان\u200cبندی')),
            ],
            options={
                'verbose_name': 'نمونه چک لیست برنامه\u200cریزی شده',
                'verbose_name_plural': 'نمونه\u200cهای چک لیست برنامه\u200cریزی شده',
                'ordering': ['-due_date', 'status'],
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='scheduled_instance',
            field=models.ForeignKey(blank=True, help_text='اگر این چک\u200cلیست از یک برنامه زمان\u200cبندی شده ایجاد شده باشد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklists', to='checklist_app.scheduledchecklistinstance', verbose_name='نمونه برنامه\u200cریزی شده'),
        ),
        migrations.AddIndex(
            model_name='scheduledchecklistinstance',
            index=models.Index(fields=['status', 'due_date'], name='checklist_a_status_52b19a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledchecklistinstance',
            index=models.Index(fields=['schedule', 'due_date'], name='checklist_a_schedul_eef032_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledchecklistinstance',
            unique_together={('schedule', 'due_date')},
        ),
    ]
