# Generated by Django 4.2 on 2025-11-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0016_contractor_user_employee_user'),
        ('anomalis', '0006_comment_file_alter_comment_comment'),
        ('BaseInfo', '0013_emergencyvehicle_has_brake_and_more'),
        ('checklist_app', '0009_checklistschedule_checklist_machine_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistschedule',
            name='target_contractor_vehicles',
            field=models.JSONField(blank=True, default=list, help_text='لیست ID ماشین\u200cهای پیمانکار هدف (مثلاً [1, 2, 3])', verbose_name='ماشین\u200cهای پیمانکار هدف'),
        ),
        migrations.AddField(
            model_name='checklistschedule',
            name='target_location_sections',
            field=models.JSONField(blank=True, default=list, help_text='لیست ID بخش\u200cهای مکانی هدف (مثلاً [1, 2, 3])', verbose_name='بخش\u200cهای مکانی هدف'),
        ),
        migrations.AddField(
            model_name='checklistschedule',
            name='target_machines',
            field=models.JSONField(blank=True, default=list, help_text='لیست ID ماشین\u200cهای هدف (مثلاً [1, 2, 3])', verbose_name='ماشین\u200cهای هدف'),
        ),
        migrations.AlterField(
            model_name='checklistschedule',
            name='target_contractor_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_checklists_old', to='contractor_management.vehicle', verbose_name='ماشین پیمانکار هدف (قدیمی)'),
        ),
        migrations.AlterField(
            model_name='checklistschedule',
            name='target_location_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_checklists_old', to='anomalis.locationsection', verbose_name='بخش مکانی هدف (قدیمی)'),
        ),
        migrations.AlterField(
            model_name='checklistschedule',
            name='target_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_checklists_old', to='BaseInfo.miningmachine', verbose_name='ماشین هدف (قدیمی)'),
        ),
    ]
