# Generated by Django 5.1.2 on 2025-01-05 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_delete_department_delete_unit'),
        ('contractor_management', '0008_alter_report_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(verbose_name='تاریخ وقوع حادثه')),
                ('incident_time', models.TimeField(verbose_name='ساعت وقوع')),
                ('incident_location', models.TextField(verbose_name='محل وقوع')),
                ('involved_equipment', models.TextField(blank=True, null=True, verbose_name='تجهیزات مرتبط با حادثه')),
                ('injury_type', models.CharField(choices=[('جراحت', 'جراحت و بریدگی'), ('شکستگی', 'شکستگی'), ('سوختگی', 'سوختگی'), ('نقص_عضو', 'نقص عضو'), ('فوت', 'فوت')], max_length=10, verbose_name='نوع جراحت')),
                ('affected_body_part', models.CharField(max_length=100, verbose_name='عضو آسیب دیده')),
                ('damage_description', models.TextField(verbose_name='شرح آسیب وارده')),
                ('related_entity', models.CharField(choices=[('کاراوران', 'شرکت کاراوران'), ('پیمانکار', 'پیمانکاران')], max_length=10, verbose_name='نوع ارتباط')),
                ('fire_truck_needed', models.BooleanField(default=False, verbose_name='آیا خودرو آتش نشانی اعزام گردید')),
                ('ambulance_needed', models.BooleanField(default=False, verbose_name='آیا آمبولانس اعزام گردید')),
                ('hospitalized', models.BooleanField(default=False, verbose_name='آیا فرد حادثه به بیمارستان اعزام گردید')),
                ('transportation_type', models.CharField(blank=True, choices=[('آمبولانس', 'آمبولانس'), ('خودرو_شخصی', 'خودرو شخصی')], max_length=15, null=True, verbose_name='نوع وسیله نقلیه')),
                ('full_description', models.TextField(verbose_name='شرح کامل حادثه با ذکر جزئیات')),
                ('initial_cause', models.TextField(verbose_name='علت وقوع حادثه در بررسی های اولیه انجام شده')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ ثبت گزارش')),
                ('report_shift', models.CharField(blank=True, editable=False, max_length=20, verbose_name='شیفت ثبت گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('involved_person', models.ManyToManyField(blank=True, related_name='involved_in_incidents', to='accounts.userprofile', verbose_name='شخص/اشخاص مرتبط با حادثه')),
                ('related_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractor_management.contractor', verbose_name='پیمانکار')),
                ('report_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_incidents', to='accounts.userprofile', verbose_name='فرد گزارش دهنده')),
            ],
        ),
    ]
