# Generated by Django 5.1.2 on 2025-01-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_department_delete_unit'),
        ('contractor_management', '0008_alter_report_unique_together'),
        ('hse_incidents', '0002_injurytype_remove_incidentreport_injury_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'verbose_name': 'گزارش حادثه', 'verbose_name_plural': 'گزارشات حوادث'},
        ),
        migrations.AlterModelOptions(
            name='injurytype',
            options={'verbose_name': 'نوع جراحت', 'verbose_name_plural': 'انواع جراحت'},
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='report_shift',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='related_contractor_employees',
            field=models.ManyToManyField(blank=True, related_name='contractor_incidents', to='contractor_management.employee', verbose_name='پرسنل پیمانکار مرتبط'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='affected_body_part',
            field=models.CharField(max_length=255, verbose_name='عضو آسیب دیده'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='ambulance_needed',
            field=models.BooleanField(default=False, verbose_name='آمبولانس اعزام گردید؟'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='fire_truck_needed',
            field=models.BooleanField(default=False, verbose_name='خودرو آتش نشانی اعزام گردید؟'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='hospitalized',
            field=models.BooleanField(default=False, verbose_name='فرد به بیمارستان اعزام گردید؟'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_location',
            field=models.TextField(verbose_name='محل وقوع حادثه'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_time',
            field=models.TimeField(verbose_name='ساعت وقوع حادثه'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='injury_type',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='hse_incidents.injurytype', verbose_name='نوع جراحت'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='involved_equipment',
            field=models.TextField(default='', verbose_name='تجهیزات مرتبط با حادثه'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='involved_person',
            field=models.ManyToManyField(blank=True, related_name='involved_incidents', to='accounts.userprofile', verbose_name='اشخاص مرتبط با حادثه'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='related_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='contractor_management.contractor', verbose_name='پیمانکار مرتبط'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='related_entity',
            field=models.CharField(max_length=255, verbose_name='نوع ارتباط'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='report_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_incidents', to='accounts.userprofile', verbose_name='نویسنده گزارش'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='transportation_type',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='نوع وسیله نقلیه جهت اعزام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='injurytype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نوع جراحت'),
        ),
    ]
