# Generated by Django 5.1.2 on 2025-01-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_incidents', '0003_alter_incidentreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='ambulance_arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان رسیدن آمبولانس'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='fire_truck_arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان رسیدن خودرو آتش نشانی'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='hospitalized_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان اعزام به بیمارستان'),
        ),
    ]
