# Generated by Django 5.1.2 on 2025-01-09 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0005_alter_anomaly_group'),
        ('hse_incidents', '0004_incidentreport_ambulance_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='incident_location',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anomalis.location', verbose_name='سایت حادثه'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anomalis.locationsection', verbose_name='محل حادثه'),
        ),
    ]
