# Generated by Django 5.1.2 on 2025-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_incidents', '0006_alter_incidentreport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsecompletionreport',
            name='patient_condition_on_dispatch',
        ),
        migrations.AddField(
            model_name='hsecompletionreport',
            name='patient_condition_blood_pressure',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='فشار خون'),
        ),
        migrations.AddField(
            model_name='hsecompletionreport',
            name='patient_condition_pulse',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='نبض'),
        ),
        migrations.AddField(
            model_name='hsecompletionreport',
            name='patient_condition_respiration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد تنفس'),
        ),
        migrations.AddField(
            model_name='hsecompletionreport',
            name='patient_condition_sop',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت هوشیاری'),
        ),
        migrations.AddField(
            model_name='hsecompletionreport',
            name='patient_condition_temperature',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='دمای بدن'),
        ),
    ]
