# Generated by Django 4.2 on 2025-12-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_incidents', '0009_incidentreport_fields_and_dashboard_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['-incident_date', '-incident_time'], 'verbose_name': 'گزارش حادثه', 'verbose_name_plural': 'گزارشات حوادث'},
        ),
    ]
