# Generated by Django 4.2 on 2025-12-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hse_incidents', '0010_alter_incidentreport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('human', 'حوادث انسانی (فردی)'), ('equipment', 'حوادث تجهیزاتی'), ('environmental', 'حوادث محیط زیستی')], max_length=20, verbose_name='دسته بندی حادثه')),
                ('name', models.CharField(max_length=255, verbose_name='نوع حادثه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع حادثه',
                'verbose_name_plural': 'انواع حادثه',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hse_incidents.incidenttype', verbose_name='نوع حادثه'),
        ),
    ]
