# Generated by Django 4.2 on 2025-12-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_incidents', '0011_incidenttype_incidentreport_incident_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('human', 'حوادث انسانی (فردی)'), ('equipment', 'حوادث تجهیزاتی'), ('environmental', 'حوادث محیط زیستی')], max_length=20, null=True, verbose_name='نوع حادثه'),
        ),
        migrations.DeleteModel(
            name='IncidentType',
        ),
    ]
