# Generated by Django 5.1.2 on 2024-12-08 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseInfo', '0011_miningmachine_contractor_and_more'),
        ('accounts', '0006_alter_userprofile_unit'),
        ('contractor_management', '0005_alter_vehicle_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingSiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='تایید شده')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('drilling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.miningblock', verbose_name='سایت حفاری')),
            ],
        ),
        migrations.CreateModel(
            name='DumpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='تایید شده')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.miningblock', verbose_name='دمپ')),
            ],
        ),
        migrations.CreateModel(
            name='HSEParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('employee', 'پرسنل'), ('contractor', 'پیمانکار')], max_length=20, verbose_name='نوع فرد')),
                ('description', models.TextField(verbose_name='شرح مشارکت')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractor_management.employee', verbose_name='فرد مرتبط')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='پرسنل مرتبط')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('employee', 'پرسنل'), ('contractor', 'پیمانکار')], max_length=20, verbose_name='نوع فرد')),
                ('description', models.TextField(verbose_name='شرح حادثه')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractor_management.employee', verbose_name='فرد مرتبط')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='پرسنل مرتبط')),
            ],
        ),
        migrations.CreateModel(
            name='HSEReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شیفت')),
                ('repair_shop_visit', models.BooleanField(default=False, verbose_name='بازدید از تعمیرگاه')),
                ('repair_shop_status', models.BooleanField(default=False, verbose_name='وضعیت تعمیرگاه')),
                ('repair_shop_comments', models.TextField(blank=True, null=True, verbose_name='توضیحات تعمیرگاه')),
                ('blasting', models.BooleanField(default=False, verbose_name='آتشباری')),
                ('next_shift_tasks', models.TextField(blank=True, null=True, verbose_name='موارد پیگیری برای شیفت بعد')),
                ('blasting_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.miningblock', verbose_name='محل آتشباری')),
                ('drilling_site_statuses', models.ManyToManyField(blank=True, to='dailyreport_hse.drillingsitestatus', verbose_name='وضعیت سایت\u200cهای حفاری')),
                ('dump_statuses', models.ManyToManyField(blank=True, to='dailyreport_hse.dumpstatus', verbose_name='وضعیت دمپ\u200cها')),
                ('hse_participation', models.ManyToManyField(blank=True, to='dailyreport_hse.hseparticipation', verbose_name='مشارکت کارکنان')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='سرشیفت')),
                ('hospital_dispatches', models.ManyToManyField(blank=True, related_name='hospital_dispatches', to='dailyreport_hse.incident', verbose_name='اعزام به بیمارستان')),
                ('incidents', models.ManyToManyField(blank=True, to='dailyreport_hse.incident', verbose_name='حوادث رخ داده')),
                ('near_misses', models.ManyToManyField(blank=True, related_name='near_misses', to='dailyreport_hse.incident', verbose_name='شبه\u200cحوادث')),
                ('penalties', models.ManyToManyField(blank=True, related_name='penalties', to='dailyreport_hse.incident', verbose_name='موارد تنبیه')),
                ('rewards', models.ManyToManyField(blank=True, related_name='rewards', to='dailyreport_hse.incident', verbose_name='موارد تشویق')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='دلیل توقف')),
                ('duration_hours', models.FloatField(verbose_name='مدت زمان توقف (ساعت)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stop_reports', to='dailyreport_hse.hsereport', verbose_name='گزارش ایمنی')),
            ],
        ),
        migrations.AddField(
            model_name='hsereport',
            name='safety_stops',
            field=models.ManyToManyField(blank=True, related_name='reports', to='dailyreport_hse.safetystop', verbose_name='توقفات ناشی از ایمنی'),
        ),
        migrations.CreateModel(
            name='WorkFrontStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='تایید شده')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('workfront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.miningblock', verbose_name='جبهه کاری')),
            ],
        ),
        migrations.AddField(
            model_name='hsereport',
            name='workfront_statuses',
            field=models.ManyToManyField(blank=True, to='dailyreport_hse.workfrontstatus', verbose_name='وضعیت جبهه\u200cهای کاری'),
        ),
    ]
