# Generated by Django 5.1.2 on 2025-02-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport_hse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiondetail',
            name='inspection',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بازرسی'),
        ),
    ]
