# Generated by Django 5.1.2 on 2024-12-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport_hse', '0002_dailyreport_work_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='shift',
            field=models.CharField(choices=[('روزکار اول', 'روزکار اول'), ('روزکار دوم', 'روزکار دوم'), ('عصرکار اول', 'عصرکار اول'), ('عصرکار دوم', 'عصرکار دوم'), ('شب کار اول', 'شب کار اول'), ('شب کار دوم', 'شب کار دوم'), ('OFF اول', 'OFF اول'), ('OFF دوم', 'OFF دوم')], max_length=10, verbose_name='شیفت کاری'),
        ),
    ]
