# Generated by Django 5.1.2 on 2025-02-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport_hse', '0002_inspectiondetail_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillingdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('safe', 'ایمن'), ('unsafe', 'ناایمن')], max_length=10, null=True, verbose_name='وضعیت حفاری'),
        ),
        migrations.AlterField(
            model_name='dumpdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('safe', 'ایمن'), ('unsafe', 'ناایمن')], max_length=10, null=True, verbose_name='وضعیت دامپ'),
        ),
        migrations.AlterField(
            model_name='followupdetail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='loadingdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('safe', 'ایمن'), ('unsafe', 'ناایمن')], max_length=10, null=True, verbose_name='وضعیت بارگیری'),
        ),
        migrations.AlterField(
            model_name='stoppagedetail',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='stoppagedetail',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت توقف'),
        ),
        migrations.AlterField(
            model_name='stoppagedetail',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان شروع'),
        ),
    ]
