# Generated by Django 5.1.2 on 2024-12-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport_hse', '0003_alter_dailyreport_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupdetail',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='followups/%Y/%m/%d//', verbose_name='فایل\u200cهای پیوست'),
        ),
    ]
