# Generated by Django 5.1.2 on 2024-12-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_unit'),
        ('dailyreport_hse', '0004_alter_followupdetail_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='افسر ایمنی'),
        ),
    ]
