# Generated by Django 5.1.2 on 2025-01-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport_hse', '0006_alter_dailyreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillingdetail',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='loadingdetail',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
