# Generated by Django 4.2 on 2025-11-27 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hse_docs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_userprofile_national_code_alter_payslip_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('icon', models.CharField(blank=True, help_text='نام آیکون Font Awesome (مثال: fa-file-alt)', max_length=50, null=True, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی موضوع',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای موضوع',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('file', models.FileField(upload_to=hse_docs.models.document_upload_path, verbose_name='فایل')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='نسخه')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.section', verbose_name='بخش')),
                ('topic_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hse_docs.topiccategory', verbose_name='دسته\u200cبندی موضوع')),
                ('unit_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.unitgroup', verbose_name='گروه')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بارگذاری شده توسط')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['topic_category', 'section', 'unit_group'], name='hse_docs_do_topic_c_3654f7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_active', '-uploaded_at'], name='hse_docs_do_is_acti_efb823_idx'),
        ),
    ]
