# Generated by Django 4.2 on 2026-08-12 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_number', models.CharField(max_length=32, unique=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('beneficiary_type', models.CharField(choices=[('EMPLOYEE', 'پرسنل'), ('DEPENDENT', 'تحت تکفل')], max_length=12)),
                ('beneficiary_account_id', models.PositiveBigIntegerField()),
                ('beneficiary_key', models.CharField(editable=False, max_length=32)),
                ('relation_snapshot', models.CharField(blank=True, max_length=50)),
                ('employee_full_name_snapshot', models.CharField(max_length=301)),
                ('beneficiary_full_name_snapshot', models.CharField(max_length=301)),
                ('personnel_no_snapshot', models.CharField(blank=True, max_length=30)),
                ('issue_date', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('USED', 'استفاده\u200cشده'), ('EXPIRED', 'منقضی'), ('CANCELLED', 'لغوشده'), ('INVOICED', 'صورت\u200cحساب\u200cشده')], default='ACTIVE', max_length=20)),
                ('source', models.CharField(choices=[('WEB', 'وب'), ('RUBIKA', 'روبیکا'), ('ADMIN', 'مدیریت'), ('PHYSICAL_LEGACY', 'فیزیکی قدیمی')], max_length=20)),
                ('legacy_letter_no', models.CharField(blank=True, max_length=80, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_gym_referrals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gym_referrals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gym_referrals', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='gym_referrals.gym')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferralSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_referrals.gym')),
                ('redeemed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usage', to='gym_referrals.referral')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_record', to='gym_referrals.referral')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='gym_referrals.referral')),
            ],
        ),
        migrations.CreateModel(
            name='GymContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('billing_policy', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='gym_referrals.gym')),
            ],
        ),
        migrations.AddConstraint(
            model_name='referralidempotencykey',
            constraint=models.UniqueConstraint(fields=('requester', 'key'), name='unique_referral_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['beneficiary_account_id', 'status', 'valid_until'], name='gym_referra_benefic_1647bf_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['gym', 'status'], name='gym_referra_gym_id_bc4b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['created_at'], name='gym_referra_created_e0dae0_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__gte', models.F('valid_from'))), name='referral_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('beneficiary_key',), name='one_active_referral_per_beneficiary'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_letter_no__isnull', False)), fields=('legacy_letter_no',), name='unique_legacy_letter_no'),
        ),
        migrations.AddConstraint(
            model_name='gymcontract',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='gym_contract_dates_valid'),
        ),
    ]
