# Generated by Django 4.2 on 2026-08-12 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='gym_referrals.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operated_gyms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='gymoperator',
            constraint=models.UniqueConstraint(fields=('gym', 'user'), name='unique_gym_operator'),
        ),
    ]
