# Generated by Django 4.2 on 2026-08-12 09:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_referrals', '0002_gymoperator_gymoperator_unique_gym_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('billing_policy', models.CharField(choices=[('ISSUED', 'معرفی\u200cنامه\u200cهای صادرشده'), ('USED', 'معرفی\u200cنامه\u200cهای استفاده\u200cشده')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('FINALIZED', 'نهایی\u200cشده'), ('APPROVED', 'تأییدشده'), ('PAID', 'پرداخت\u200cشده'), ('CANCELLED', 'لغوشده')], default='DRAFT', max_length=12)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gym_invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gym_invoices', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='gym_referrals.gym')),
            ],
            options={
                'ordering': ('-period_start', 'gym__name'),
            },
        ),
        migrations.AddField(
            model_name='gymcontract',
            name='price_per_referral',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='gymcontract',
            name='billing_policy',
            field=models.CharField(choices=[('ISSUED', 'معرفی\u200cنامه\u200cهای صادرشده'), ('USED', 'معرفی\u200cنامه\u200cهای استفاده\u200cشده')], default='ISSUED', max_length=10),
        ),
        migrations.CreateModel(
            name='GymInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_account_id', models.PositiveBigIntegerField()),
                ('employee_account_id', models.PositiveBigIntegerField()),
                ('beneficiary_name_snapshot', models.CharField(max_length=301)),
                ('employee_name_snapshot', models.CharField(max_length=301)),
                ('personnel_no_snapshot', models.CharField(blank=True, max_length=30)),
                ('referral_number', models.CharField(max_length=32)),
                ('referral_source', models.CharField(choices=[('WEB', 'وب'), ('RUBIKA', 'روبیکا'), ('ADMIN', 'مدیریت'), ('PHYSICAL_LEGACY', 'فیزیکی قدیمی')], max_length=20)),
                ('usage_date', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('is_billable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='gym_referrals.gyminvoice')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='gym_referrals.referral')),
                ('referral_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='gym_referrals.referralusage')),
            ],
        ),
        migrations.AddField(
            model_name='gyminvoice',
            name='gym_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='gym_referrals.gymcontract'),
        ),
        migrations.AddField(
            model_name='gyminvoice',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_gym_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gyminvoiceitem',
            index=models.Index(fields=['invoice', 'referral_number'], name='gym_referra_invoice_e1aae9_idx'),
        ),
        migrations.AddConstraint(
            model_name='gyminvoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='gym_invoice_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='gyminvoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('line_total', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')))), name='gym_invoice_item_total_consistent'),
        ),
        migrations.AddConstraint(
            model_name='gyminvoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_billable', True), ('referral_usage__isnull', True)), fields=('referral',), name='unique_issued_referral_invoice_item'),
        ),
        migrations.AddConstraint(
            model_name='gyminvoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_billable', True), ('referral_usage__isnull', False)), fields=('referral_usage',), name='unique_usage_invoice_item'),
        ),
        migrations.AddIndex(
            model_name='gyminvoice',
            index=models.Index(fields=['gym', 'period_year', 'period_month', 'status'], name='gym_referra_gym_id_c87f5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='gyminvoice',
            constraint=models.CheckConstraint(check=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='gym_invoice_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='gyminvoice',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='gym_invoice_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='gyminvoice',
            constraint=models.CheckConstraint(check=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('adjustment_amount')))), name='gym_invoice_total_consistent'),
        ),
        migrations.AddConstraint(
            model_name='gyminvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('gym', 'gym_contract', 'period_year', 'period_month'), name='unique_active_gym_invoice_period'),
        ),
    ]
