# Generated by Django 4.2 on 2026-08-12 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_invoice_item_snapshots(apps, schema_editor):
    Item = apps.get_model('gym_referrals', 'GymInvoiceItem')
    batch = []
    for item in Item.objects.select_related('referral').iterator(chunk_size=1000):
        item.issue_date = item.referral.issue_date
        item.relation_snapshot = item.referral.relation_snapshot
        batch.append(item)
        if len(batch) == 1000:
            Item.objects.bulk_update(batch, ('issue_date', 'relation_snapshot'), batch_size=1000)
            batch.clear()
    if batch:
        Item.objects.bulk_update(batch, ('issue_date', 'relation_snapshot'), batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_referrals', '0003_gyminvoice_gymcontract_price_per_referral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymInvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gyminvoice',
            options={'ordering': ('-period_start', 'gym__name'), 'permissions': [('generate_gym_invoice', 'Can generate gym invoice'), ('finalize_gym_invoice', 'Can finalize gym invoice'), ('approve_gym_invoice', 'Can approve gym invoice'), ('mark_gym_invoice_paid', 'Can mark gym invoice paid'), ('cancel_gym_invoice', 'Can cancel gym invoice'), ('adjust_gym_invoice', 'Can adjust gym invoice'), ('export_gym_invoice', 'Can export gym invoice')]},
        ),
        migrations.AddField(
            model_name='gyminvoiceitem',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gyminvoiceitem',
            name='relation_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(backfill_invoice_item_snapshots, migrations.RunPython.noop),
        migrations.CreateModel(
            name='GymInvoiceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='gym_referrals.gyminvoice')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
