# Generated by Django 4.2.30 on 2026-08-27 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_referrals', '0004_gyminvoicesequence_alter_gyminvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='account_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_account', to=settings.AUTH_USER_MODEL, verbose_name='کاربر باشگاه'),
        ),
    ]
