# Generated by Django 4.2.30 on 2026-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_referrals', '0005_gym_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='accepts_female',
            field=models.BooleanField(default=True, verbose_name='پذیرش زنان'),
        ),
        migrations.AddField(
            model_name='gym',
            name='accepts_male',
            field=models.BooleanField(default=True, verbose_name='پذیرش مردان'),
        ),
    ]
