# Generated by Django 5.1.2 on 2025-01-08 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseInfo', '0011_miningmachine_contractor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('shift', models.CharField(blank=True, max_length=20, null=True, verbose_name='شیفت کاری')),
                ('shift_group', models.CharField(blank=True, max_length=2, null=True, verbose_name='گروه شیفت')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.miningmachine', verbose_name='ماشین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'چک لیست',
                'verbose_name_plural': 'چک لیست ها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('is_required', models.BooleanField(default=True, verbose_name='اجباری')),
                ('question_type', models.CharField(choices=[('text', 'متنی'), ('option', 'گزینه ای')], default='text', max_length=20, verbose_name='نوع سوال')),
                ('options', models.TextField(blank=True, null=True, verbose_name='گزینه ها (با کاما جدا شود)')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.typemachine', verbose_name='نوع دستگاه')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='پاسخ متنی')),
                ('selected_option', models.CharField(blank=True, max_length=255, null=True, verbose_name='گزینه انتخاب شده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_checklist.checklist', verbose_name='چک لیست')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_checklist.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
            },
        ),
    ]
