# Generated by Django 5.1.2 on 2025-05-12 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseInfo', '0013_emergencyvehicle_has_brake_and_more'),
        ('anomalis', '0006_comment_file_alter_comment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FireExtinguisherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('agent', models.CharField(max_length=100, verbose_name='عامل خاموش کننده')),
                ('use_class', models.CharField(max_length=100, verbose_name='کلاس کاربری')),
                ('inspection_interval_months', models.PositiveIntegerField(verbose_name='فاصله بازرسی (ماه)')),
                ('service_interval_years', models.PositiveIntegerField(verbose_name='فاصله سرویس (سال)')),
                ('pressure_test_interval_years', models.PositiveIntegerField(verbose_name='فاصله تست فشار (سال)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع کپسول آتش\u200cنشانی',
                'verbose_name_plural': 'انواع کپسول\u200cهای آتش\u200cنشانی',
            },
        ),
        migrations.CreateModel(
            name='FireExtinguisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_tag', models.CharField(max_length=50, unique=True, verbose_name='کد سریال')),
                ('capacity_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ظرفیت')),
                ('capacity_unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('L', 'لیتر')], max_length=20, verbose_name='واحد ظرفیت')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='سازنده')),
                ('model_number', models.CharField(max_length=50, verbose_name='شماره مدل')),
                ('purchase_date', models.DateField(verbose_name='تاریخ خرید')),
                ('manufacture_date', models.DateField(verbose_name='تاریخ ساخت')),
                ('commission_date', models.DateField(verbose_name='تاریخ بهره\u200cبرداری')),
                ('expected_lifespan_years', models.PositiveIntegerField(verbose_name='عمر مفید (سال)')),
                ('status', models.CharField(choices=[('operational', 'عملیاتی'), ('needs_maintenance', 'نیازمند تعمیر'), ('expired', 'منقضی شده'), ('under_test', 'در انتظار تست'), ('disposed', 'مستهلک شده'), ('reserved', 'رزرو شده')], default='operational', max_length=20, verbose_name='وضعیت')),
                ('location_type', models.CharField(choices=[('section', 'بخش'), ('machine', 'دستگاه')], default='section', max_length=20, verbose_name='نوع مکان')),
                ('last_serviced_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین سرویس')),
                ('next_scheduled_service_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سرویس بعدی')),
                ('pressure_test_due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تست فشار')),
                ('replacement_notes', models.TextField(blank=True, verbose_name='توضیحات جایگزینی')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('location_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.miningmachine', verbose_name='دستگاه')),
                ('location_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anomalis.locationsection', verbose_name='بخش')),
                ('replaced_by_extinguisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_for', to='fire_extinguisher_management.fireextinguisher', verbose_name='جایگزین شده با')),
                ('replaces_extinguisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_from', to='fire_extinguisher_management.fireextinguisher', verbose_name='جایگزین شده از')),
                ('extinguisher_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fire_extinguisher_management.fireextinguishertype', verbose_name='نوع کپسول')),
            ],
            options={
                'verbose_name': 'کپسول آتش\u200cنشانی',
                'verbose_name_plural': 'کپسول\u200cهای آتش\u200cنشانی',
                'ordering': ['-commission_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='تاریخ سرویس')),
                ('service_type', models.CharField(choices=[('inspection', 'بازرسی'), ('maintenance', 'تعمیر و نگهداری'), ('pressure_test', 'تست فشار'), ('refill', 'پر کردن مجدد')], max_length=20, verbose_name='نوع سرویس')),
                ('outcome', models.CharField(choices=[('passed', 'قبول'), ('failed', 'رد'), ('needs_repair', 'نیازمند تعمیر')], max_length=20, verbose_name='نتیجه')),
                ('performed_by_external', models.CharField(blank=True, max_length=100, verbose_name='انجام دهنده (خارجی)')),
                ('pressure_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='فشار')),
                ('weight_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='وزن')),
                ('actions_taken', models.TextField(verbose_name='اقدامات انجام شده')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('extinguisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire_extinguisher_management.fireextinguisher', verbose_name='کپسول')),
                ('performed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انجام دهنده (کاربر)')),
            ],
            options={
                'verbose_name': 'سابقه سرویس',
                'verbose_name_plural': 'سوابق سرویس',
                'ordering': ['-service_date'],
            },
        ),
    ]
