# Generated by Django 4.2 on 2025-11-30 08:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fire_extinguisher_management', '0003_remove_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireextinguisher',
            name='last_charge_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین شارژ'),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='next_charge_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شارژ بعدی'),
        ),
        migrations.CreateModel(
            name='MonthlyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_charge_status', models.BooleanField(default=False, verbose_name='وضعیت شارژ (فشار)')),
                ('gauge_status', models.BooleanField(default=False, verbose_name='وضعیت گیج')),
                ('hose_nozzle_status', models.BooleanField(default=False, verbose_name='وضعیت شیلنگ و نازل')),
                ('body_condition', models.BooleanField(default=False, verbose_name='وضعیت بدنه')),
                ('safety_pin_seal_status', models.BooleanField(default=False, verbose_name='وضعیت ضامن و پلمپ')),
                ('inspection_date', models.DateField(default=datetime.date.today, verbose_name='تاریخ بازدید')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('extinguisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_inspections', to='fire_extinguisher_management.fireextinguisher', verbose_name='کپسول آتش\u200cنشانی')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بازدید کننده')),
            ],
            options={
                'verbose_name': 'بازدید ماهانه',
                'verbose_name_plural': 'بازدیدهای ماهانه',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AddIndex(
            model_name='monthlyinspection',
            index=models.Index(fields=['-inspection_date'], name='fire_exting_inspect_84d609_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyinspection',
            index=models.Index(fields=['extinguisher', '-inspection_date'], name='fire_exting_extingu_59536c_idx'),
        ),
    ]
