# Generated by Django 5.1.2 on 2025-01-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_part_section_remove_unit_department_and_more'),
        ('permissions', '0002_departmentpermission_positionpermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitpermission',
            name='unit',
        ),
        migrations.AlterField(
            model_name='positionpermission',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.position', verbose_name='سمت'),
        ),
        migrations.CreateModel(
            name='PartPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100, verbose_name='نام ویو')),
                ('can_view', models.BooleanField(default=False, verbose_name='مشاهده')),
                ('can_add', models.BooleanField(default=False, verbose_name='افزودن')),
                ('can_edit', models.BooleanField(default=False, verbose_name='ویرایش')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.part', verbose_name='قسمت')),
            ],
        ),
        migrations.CreateModel(
            name='SectionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100, verbose_name='نام ویو')),
                ('can_view', models.BooleanField(default=False, verbose_name='مشاهده')),
                ('can_add', models.BooleanField(default=False, verbose_name='افزودن')),
                ('can_edit', models.BooleanField(default=False, verbose_name='ویرایش')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.section', verbose_name='بخش')),
            ],
        ),
        migrations.CreateModel(
            name='UnitGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100, verbose_name='نام ویو')),
                ('can_view', models.BooleanField(default=False, verbose_name='مشاهده')),
                ('can_add', models.BooleanField(default=False, verbose_name='افزودن')),
                ('can_edit', models.BooleanField(default=False, verbose_name='ویرایش')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('unit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.unitgroup', verbose_name='گروه')),
            ],
        ),
        migrations.DeleteModel(
            name='DepartmentPermission',
        ),
        migrations.DeleteModel(
            name='UnitPermission',
        ),
    ]
