# Generated by Django 5.1.2 on 2025-01-04 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_remove_unitpermission_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100, verbose_name='نام ویو')),
                ('can_view', models.BooleanField(default=False, verbose_name='مشاهده')),
                ('can_add', models.BooleanField(default=False, verbose_name='افزودن')),
                ('can_edit', models.BooleanField(default=False, verbose_name='ویرایش')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
