# Generated by Django 5.1.2 on 2025-04-18 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_notification_meeting'),
        ('meetings', '0004_alter_meeting_date_alter_meeting_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان\u200cها'},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'اطلاع\u200cرسانی'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('error', 'خطا'), ('meeting', 'جلسه')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_n_user_id_5c2164_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='dashboard_n_user_id_b572f4_idx'),
        ),
    ]
