# Generated by Django 4.2 on 2025-11-17 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام قالب')),
                ('template_id', models.IntegerField(unique=True, verbose_name='شناسه قالب در SMS.ir')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('template_text', models.TextField(help_text='از {PARAM_NAME} برای پارامترها استفاده کنید', verbose_name='متن قالب')),
                ('parameters', models.JSONField(default=list, help_text='مثال: ["NAME", "DATE", "TIME"]', verbose_name='لیست پارامترها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('usage_count', models.IntegerField(default=0, verbose_name='تعداد استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'قالب پیامک',
                'verbose_name_plural': 'قالب\u200cهای پیامک',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=20, verbose_name='شماره موبایل')),
                ('template_id', models.IntegerField(verbose_name='شناسه قالب')),
                ('parameters', models.JSONField(default=dict, verbose_name='پارامترهای قالب')),
                ('status', models.CharField(choices=[('pending', 'در صف ارسال'), ('sent', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('failed', 'ناموفق'), ('rate_limited', 'محدود شده (Rate Limit)')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='پاسخ SMS.ir')),
                ('track_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شناسه رهگیری')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ایجاد')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه تقریبی (ریال)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی درخواست')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ پیامک',
                'verbose_name_plural': 'لاگ\u200cهای پیامک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['mobile_number', '-created_at'], name='dashboard_s_mobile__7816d9_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_s_user_id_a55deb_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['status', '-created_at'], name='dashboard_s_status_dc26f0_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['template_id', '-created_at'], name='dashboard_s_templat_5a34bb_idx'),
        ),
    ]
