# Generated by Django 5.1.2 on 2024-10-22 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(blank=True, default='', max_length=10, verbose_name='کد پرسنلی')),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('group', models.CharField(blank=True, choices=[('A', 'گروه A'), ('B', 'گروه B'), ('C', 'گروه C'), ('D', 'گروه D'), ('G', 'گروه G')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
