# Generated by Django 5.1.2 on 2025-01-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام قسمت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'قسمت',
                'verbose_name_plural': 'قسمت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام بخش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='unit',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='position',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'سمت', 'verbose_name_plural': 'سمت\u200cها'},
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام سمت'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'گروه A'), ('B', 'گروه B'), ('C', 'گروه C'), ('D', 'گروه D'), ('G', 'گروه G'), ('G2', 'گروه G2')], max_length=2, verbose_name='گروه کاری'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.position', verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.part', verbose_name='قسمت'),
        ),
        migrations.AddField(
            model_name='part',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.section', verbose_name='بخش'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.section', verbose_name='بخش'),
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام گروه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.part', verbose_name='قسمت')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه\u200cها',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='unit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.unitgroup', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.unitgroup', verbose_name='گروه'),
        ),
    ]
