# Generated by Django 5.1.2 on 2025-04-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_department_delete_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature_no_bg',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='امضای کاربر بدون پس\u200cزمینه'),
        ),
    ]
