# Generated by Django 5.1.2 on 2025-04-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_signature_no_bg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='signature_no_bg',
        ),
    ]
