# Generated by Django 5.1.2 on 2025-04-14 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userprofile_signature_no_bg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_base', models.CharField(choices=[('1', 'پایه یک'), ('2', 'پایه دو'), ('3', 'پایه سه')], max_length=1, verbose_name='پایه گواهینامه')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('has_special', models.BooleanField(default=False, verbose_name='ویژه دارد')),
                ('special_codes', models.JSONField(blank=True, default=list, verbose_name='کدهای ویژه')),
                ('front_image', models.ImageField(upload_to='license_images/', verbose_name='عکس روی گواهینامه')),
                ('back_image', models.ImageField(upload_to='license_images/', verbose_name='عکس پشت گواهینامه')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه\u200cها',
            },
        ),
    ]
