# Generated by Django 5.1.4 on 2025-10-28 20:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_driverlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='back_image',
            field=models.ImageField(upload_to='license_images/', validators=[core.validators.validate_image_file], verbose_name='عکس پشت گواهینامه'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='front_image',
            field=models.ImageField(upload_to='license_images/', validators=[core.validators.validate_image_file], verbose_name='عکس روی گواهینامه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', validators=[core.validators.validate_signature_image], verbose_name='امضای کاربر'),
        ),
    ]
