# Generated by Django 5.2.4 on 2025-11-07 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_driverlicense_back_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payslips/%Y/%m/', verbose_name='فایل فیش حقوقی')),
                ('month', models.IntegerField(verbose_name='ماه')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بارگذاری شده توسط')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='accounts.userprofile', verbose_name='پروفایل کاربر')),
            ],
            options={
                'verbose_name': 'فیش حقوقی',
                'verbose_name_plural': 'فیش\u200cهای حقوقی',
                'ordering': ['-year', '-month'],
                'unique_together': {('user_profile', 'year', 'month')},
            },
        ),
    ]
