# Generated by Django 4.2 on 2025-11-13 14:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='file',
            field=models.FileField(upload_to=accounts.models.payslip_upload_path, verbose_name='فایل فیش حقوقی'),
        ),
    ]
