# Generated by Django 4.2 on 2026-07-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_national_code_alter_payslip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='children_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد فرزندان'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=150, verbose_name='رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='وضعیت تاهل'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_experience_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سابقه کار (روز)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workshop_job_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='عنوان شغل کارگاه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='شماره تماس'),
        ),
    ]
