# Generated by Django 4.2 on 2026-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userprofile_birth_date_userprofile_children_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='military_service_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='وضعیت خدمت سربازی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, verbose_name='محل تولد'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='واحد'),
        ),
    ]
