# Generated by Django 5.1.2 on 2025-03-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل لغو'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'برنامه\u200cریزی شده'), ('cancelled', 'لغو شده'), ('completed', 'برگزار شده')], default='scheduled', max_length=20, verbose_name='وضعیت جلسه'),
        ),
    ]
