# Generated by Django 5.1.2 on 2025-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_cancellation_reason_meeting_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'جلسه', 'verbose_name_plural': 'جلسات'},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(default='23:59', verbose_name='ساعت پایان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مکان'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
