# Generated by Django 5.1.2 on 2025-03-19 04:40

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_meeting_options_remove_meeting_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(verbose_name='ساعت شروع'),
        ),
    ]
