# Generated by Django 5.1.4 on 2025-10-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_date_alter_meeting_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
    ]
