# Generated by Django 4.2 on 2026-07-24 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0005_alter_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_meetings', to=settings.AUTH_USER_MODEL, verbose_name='لغوکننده'),
        ),
    ]
