# Generated by Django 4.2 on 2026-07-24 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def approve_existing_meetings(apps, schema_editor):
    Meeting = apps.get_model('meetings', 'Meeting')
    Meeting.objects.update(approval_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0006_meeting_cancelled_at_meeting_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت تأیید'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_meetings', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='دلیل رد'),
        ),
        migrations.RunPython(approve_existing_meetings, migrations.RunPython.noop),
    ]
