# Generated by Django 5.1.2 on 2025-04-25 13:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_driverlicense'),
        ('contractor_management', '0012_alter_report_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام خدمت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'خدمت درمانی',
                'verbose_name_plural': 'خدمات درمانی',
            },
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی دارو',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای دارو',
            },
        ),
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_type', models.CharField(choices=[('company', 'پرسنل شرکت'), ('contractor', 'پرسنل پیمانکار')], max_length=20, verbose_name='نوع پرسنل')),
                ('visit_reason', models.TextField(verbose_name='علت مراجعه')),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان مراجعه')),
                ('doctor_recommendation', models.TextField(verbose_name='توصیه پزشک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='پرسنل شرکت')),
                ('contractor_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractor_management.employee', verbose_name='پرسنل پیمانکار')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to='accounts.userprofile', verbose_name='ثبت کننده')),
                ('services', models.ManyToManyField(to='emergency_services.medicalservice', verbose_name='خدمات درمانی')),
            ],
            options={
                'verbose_name': 'مراجعه پزشکی',
                'verbose_name_plural': 'مراجعات پزشکی',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دارو')),
                ('quantity', models.PositiveIntegerField(verbose_name='موجودی فعلی')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('critical_threshold', models.PositiveIntegerField(verbose_name='حد بحرانی هشدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emergency_services.medicinecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
            },
        ),
        migrations.CreateModel(
            name='MedicineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emergency_services.medicine', verbose_name='دارو')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_usages', to='emergency_services.medicalvisit', verbose_name='مراجعه')),
            ],
            options={
                'verbose_name': 'استفاده دارو',
                'verbose_name_plural': 'استفاده\u200cهای دارو',
            },
        ),
        migrations.CreateModel(
            name='MedicineReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد برگشتی')),
                ('return_reason', models.TextField(verbose_name='دلیل برگشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='برگشت دهنده')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_services.medicineusage', verbose_name='مصرف دارو')),
            ],
            options={
                'verbose_name': 'برگشت دارو',
                'verbose_name_plural': 'برگشت\u200cهای دارو',
            },
        ),
    ]
