# Generated by Django 5.1.2 on 2025-04-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام بیمارستان')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'بیمارستان',
                'verbose_name_plural': 'بیمارستان\u200cها',
            },
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='hospital_admission_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پذیرش در بیمارستان'),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='hospital_diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='تشخیص بیمارستان'),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='hospital_discharge_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ترخیص از بیمارستان'),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emergency_services.hospital', verbose_name='بیمارستان'),
        ),
    ]
