# Generated by Django 5.1.2 on 2025-04-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0002_hospital_medicalvisit_hospital_admission_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام تجهیز')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='شماره سریال')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('last_calibration_date', models.DateField(verbose_name='تاریخ آخرین کالیبراسیون')),
                ('next_calibration_date', models.DateField(verbose_name='تاریخ کالیبراسیون بعدی')),
                ('calibration_alert_days', models.PositiveIntegerField(default=30, verbose_name='تعداد روز هشدار قبل از کالیبراسیون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تجهیز اورژانس',
                'verbose_name_plural': 'تجهیزات اورژانس',
            },
        ),
    ]
