# Generated by Django 4.2 on 2025-11-30 06:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0003_emergencyequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='drug_type',
            field=models.CharField(choices=[('Solid', 'جامد (قرص/آمپول)'), ('Liquid', 'مایع (شربت)')], default='Solid', max_length=10, verbose_name='نوع دارو'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='total_unit_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='برای داروهای مایع: حجم کل یک واحد (مثلاً 100 برای یک شیشه 100 سی\u200cسی)', max_digits=10, null=True, verbose_name='حجم کل واحد (سی\u200cسی)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='critical_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='حد بحرانی هشدار'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='موجودی فعلی'),
        ),
        migrations.AlterField(
            model_name='medicinereturn',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='برای داروهای مایع: مقدار بر اساس سی\u200cسی وارد شود. برای سایر داروها: تعداد واحد', max_digits=10, verbose_name='تعداد/حجم برگشتی (سی\u200cسی برای مایعات)'),
        ),
        migrations.AlterField(
            model_name='medicineusage',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='برای داروهای مایع: مقدار بر اساس سی\u200cسی وارد شود. برای سایر داروها: تعداد واحد', max_digits=10, verbose_name='تعداد/حجم (سی\u200cسی برای مایعات)'),
        ),
    ]
