# Generated by Django 4.2 on 2025-12-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0005_expiredmedicinelog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expiredmedicinelog',
            new_name='emergency_s_disposa_cec8d7_idx',
            old_name='emergency_s_disposal_idx',
        ),
        migrations.RenameIndex(
            model_name='expiredmedicinelog',
            new_name='emergency_s_detecte_a22402_idx',
            old_name='emergency_s_detected_idx',
        ),
    ]
