# Generated by Django 5.1.2 on 2024-11-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'نوع آنومالی',
                'verbose_name_plural': 'نوع\u200cهای آنومالی',
            },
        ),
        migrations.CreateModel(
            name='HSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'نوع آنومالی HSE',
                'verbose_name_plural': 'نوع\u200cهای آنومالی HSE',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'محل آنومالی',
                'verbose_name_plural': 'محل\u200cهای آنومالی',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=20, verbose_name='اولویت')),
            ],
            options={
                'verbose_name': 'اولویت ',
                'verbose_name_plural': 'اولویت ها',
            },
        ),
        migrations.CreateModel(
            name='AnomalyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='شرح آنومالی')),
                ('hse_type', models.CharField(choices=[('H', 'Health'), ('S', 'Safety'), ('E', 'Environment')], max_length=1, verbose_name='نوع HSE')),
                ('anomalytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.anomalytype', verbose_name='نوع آنومالی')),
            ],
            options={
                'verbose_name': 'شرح آنومالی',
                'verbose_name_plural': 'شرح\u200cهای آنومالی',
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hse_type', models.CharField(choices=[('H', 'Health'), ('S', 'Safety'), ('E', 'Environment')], max_length=1, verbose_name='نوع HSE')),
                ('group', models.CharField(choices=[('A', 'گروه A'), ('B', 'گروه B'), ('C', 'گروه C'), ('D', 'گروه D'), ('G', 'گروه G')], max_length=1, verbose_name='گروه کاری')),
                ('description', models.TextField(verbose_name='شرح آنومالی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('action', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='anomalies/%Y/%m/%d', verbose_name='تصویر آنومالی')),
                ('is_request_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_anomalies', to='accounts.userprofile', verbose_name='ایجاد کننده')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_anomalies', to='accounts.userprofile', verbose_name='پیگیری')),
                ('anomalydescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.anomalydescription', verbose_name='شرح آنومالی')),
                ('anomalytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.anomalytype', verbose_name='نوع آنومالی')),
            ],
            options={
                'verbose_name': 'آنومالی',
                'verbose_name_plural': 'آنومالی ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='کامنت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='anomalis.anomaly', verbose_name='آنومالی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='anomalis.comment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='شرح عملیات اصلاحی')),
                ('anomali_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.anomalydescription', verbose_name='نوع آنومالی')),
            ],
            options={
                'verbose_name': 'عملیات اصلاحی',
                'verbose_name_plural': 'عملیات\u200cهای اصلاحی',
            },
        ),
        migrations.AddField(
            model_name='anomaly',
            name='correctiveaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.correctiveaction', verbose_name='عملیات اصلاحی'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.location', verbose_name='محل آنومالی'),
        ),
        migrations.CreateModel(
            name='LocationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.location')),
            ],
            options={
                'verbose_name': 'بخش محل',
                'verbose_name_plural': 'بخش های محل ها',
            },
        ),
        migrations.AddField(
            model_name='anomaly',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='anomalis.locationsection', verbose_name='بخش محل '),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.priority', verbose_name='اولویت'),
        ),
    ]
