# Generated by Django 5.1.1 on 2024-10-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='image',
            field=models.ImageField(default=1, upload_to='anomalies/%Y/%m/%d', verbose_name='تصویر آنومالی'),
            preserve_default=False,
        ),
    ]
