# Generated by Django 5.1.1 on 2024-10-10 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveaction',
            name='anomali_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.anomalydescription', verbose_name='نوع آنومالی'),
        ),
    ]
