# Generated by Django 5.1.1 on 2024-10-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0002_alter_correctiveaction_anomali_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='hse_type',
            field=models.CharField(choices=[('H', 'Health'), ('S', 'Safety'), ('E', 'Environment')], max_length=1, verbose_name='نوع HSE'),
        ),
    ]
