# Generated by Django 5.1.1 on 2024-10-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0002_anomaly_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anomalies/%Y/%m/%d', verbose_name='تصویر آنومالی'),
        ),
    ]
