# Generated by Django 5.1.1 on 2024-10-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_group'),
        ('anomalis', '0002_alter_anomaly_created_by_alter_anomaly_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_anomalies', to='accounts.userprofile', verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='followup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_anomalies', to='accounts.userprofile', verbose_name='پیگیری'),
        ),
    ]
