# Generated by Django 5.1.1 on 2024-10-04 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0003_correctiveaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomaly',
            options={'verbose_name': 'ناهنجاری', 'verbose_name_plural': 'ناهنجاری\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='anomalytype',
            options={'verbose_name': 'نوع ناهنجاری', 'verbose_name_plural': 'نوع\u200cهای ناهنجاری'},
        ),
        migrations.AlterModelOptions(
            name='correctiveaction',
            options={'verbose_name': 'عملیات اصلاحی', 'verbose_name_plural': 'عملیات\u200cهای اصلاحی'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'محل ناهنجاری', 'verbose_name_plural': 'محل\u200cهای ناهنجاری'},
        ),
        migrations.AddField(
            model_name='anomaly',
            name='action',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='correctiveaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anomalis.correctiveaction', verbose_name='عملیات اصلاحی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='anomalytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.anomalytype', verbose_name='نوع ناهنجاری'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_anomalies', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='description',
            field=models.TextField(verbose_name='شرح'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='followup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_anomalies', to=settings.AUTH_USER_MODEL, verbose_name='پیگیری'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.location', verbose_name='محل ناهنجاری'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='anomali_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.anomalytype', verbose_name='نوع ناهنجاری'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='description',
            field=models.TextField(max_length=500, verbose_name='شرح عملیات اصلاحی'),
        ),
    ]
