# Generated by Django 5.1.2 on 2024-11-25 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0003_alter_anomaly_description_alter_anomaly_hse_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_anomalies', to=settings.AUTH_USER_MODEL, verbose_name='تأیید\u200cکننده'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_anomalies', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده'),
        ),
    ]
