# Generated by Django 5.1.1 on 2024-10-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0003_alter_anomaly_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='priority',
            field=models.CharField(max_length=20, verbose_name='اولویت'),
        ),
    ]
