# Generated by Django 5.1.1 on 2024-10-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0004_alter_anomaly_options_alter_anomalytype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'برچسب ',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
    ]
