# Generated by Django 5.1.1 on 2024-10-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0004_alter_anomaly_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalis.priority', verbose_name='اولویت'),
        ),
    ]
