# Generated by Django 5.1.1 on 2024-10-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0005_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anomalis.tags', verbose_name='برچسب'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=20, verbose_name='برچسب'),
        ),
    ]
