# Generated by Django 5.1.2 on 2025-02-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0005_alter_anomaly_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comment_files/%Y/%m/%d/', verbose_name='فایل پیوست'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='کامنت'),
        ),
    ]
