# Generated by Django 5.1.1 on 2024-10-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0006_anomaly_tag_alter_tags_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomaly',
            name='tag',
        ),
        migrations.AddField(
            model_name='anomaly',
            name='tag',
            field=models.ManyToManyField(to='anomalis.tags', verbose_name='برچسب'),
        ),
    ]
