# Generated by Django 5.1.1 on 2024-10-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0007_comment_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='is_request_sent',
            field=models.BooleanField(default=False),
        ),
    ]
