# Generated by Django 4.2 on 2026-02-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loadinghaulingreport',
            new_name='mining_oper_date_3b458c_idx',
            old_name='mining_oper_date_f56ce2_idx',
        ),
        migrations.RenameIndex(
            model_name='loadinghaulingreport',
            new_name='mining_oper_loader__68c4da_idx',
            old_name='mining_oper_loader__54d07d_idx',
        ),
        migrations.RenameIndex(
            model_name='machineactivity',
            new_name='mining_oper_date_afcb20_idx',
            old_name='mining_oper_date_970ab8_idx',
        ),
        migrations.RenameIndex(
            model_name='machineactivity',
            new_name='mining_oper_machine_86f957_idx',
            old_name='mining_oper_machine_87e114_idx',
        ),
    ]
