# Generated by Django 4.2 on 2026-02-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0003_dumpcountsession_dumpcountevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dumpcountevent',
            new_name='mining_oper_session_38e3a3_idx',
            old_name='mining_oper_session_4e6f58_idx',
        ),
        migrations.RenameIndex(
            model_name='dumpcountsession',
            new_name='mining_oper_date_aa885b_idx',
            old_name='mining_oper_date_43c403_idx',
        ),
    ]
