# Generated by Django 4.2 on 2026-02-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0013_emergencyvehicle_has_brake_and_more'),
        ('mining_operations', '0004_rename_mining_oper_session_4e6f58_idx_mining_oper_session_38e3a3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadinghaulingreport',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loading_hauling_reports', to='BaseInfo.miningblock', verbose_name='شماره بلوک'),
        ),
        migrations.AddField(
            model_name='loadinghaulingreport',
            name='dump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loading_hauling_reports', to='BaseInfo.dump', verbose_name='محل تخلیه (دامپ)'),
        ),
        migrations.RemoveField(
            model_name='loadinghaulingreport',
            name='block_number',
        ),
        migrations.AddField(
            model_name='dumpcountsession',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dump_count_sessions', to='BaseInfo.miningblock', verbose_name='شماره بلوک'),
        ),
        migrations.AddField(
            model_name='dumpcountsession',
            name='dump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dump_count_sessions', to='BaseInfo.dump', verbose_name='محل تخلیه (دامپ)'),
        ),
        migrations.RemoveField(
            model_name='dumpcountsession',
            name='block_number',
        ),
    ]
