# Generated by Django 4.2 on 2026-02-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0013_emergencyvehicle_has_brake_and_more'),
        ('mining_operations', '0005_block_dump_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpcountsession',
            name='loader_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dump_count_sessions_as_loader', to='BaseInfo.miningmachine', verbose_name='ماشین بارکننده'),
        ),
    ]
