# Generated by Django 4.2 on 2026-02-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0006_dumpcountsession_loader_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumpcountevent',
            name='dumper_code',
        ),
    ]
