# Generated by Django 4.2 on 2026-02-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0005_loading_hauling_add_dumper_operator_name'),
        ('mining_operations', '0008_dumpcountsession_mineral_type'),
    ]

    operations = [
    ]
