# Generated by Django 4.2 on 2026-02-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0009_merge_20260223_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineactivity',
            name='stop_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='شرح علت توقف'),
        ),
        migrations.AlterField(
            model_name='machineactivity',
            name='stop_reason',
            field=models.CharField(blank=True, choices=[('breakdown', 'خرابی'), ('service', 'سرویس'), ('not_ready', 'بی آمادگی'), ('weather', 'جوی'), ('loader_breakdown', 'خرابی بارکننده')], max_length=20, null=True, verbose_name='علت توقف'),
        ),
    ]
