# Generated by Django 5.1.2 on 2024-10-25 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پیمانکار')),
                ('contact_info', models.CharField(blank=True, max_length=255, verbose_name='اطلاعات تماس')),
            ],
        ),
        migrations.CreateModel(
            name='MiningBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=100, verbose_name='نام بلوک')),
                ('status', models.CharField(choices=[('initial_preparation', 'آماده سازی اولیه'), ('ready_for_drilling', 'آماده حفاری'), ('ready_for_blasting', 'آماده آتش باری'), ('ready_for_loading', 'آماده بارگیری'), ('loading', 'در حال بارگیری'), ('completed', 'اتمام بلوک')], default='initial_preparation', max_length=20, verbose_name='وضعیت بلوک')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='موقعیت بلوک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100, verbose_name='نام خودرو')),
                ('vehicle_type', models.CharField(choices=[('pickup truck', 'وانت'), ('riding', 'سواری')], max_length=50, verbose_name='نوع خودرو')),
                ('license_plate', models.CharField(max_length=15, unique=True, verbose_name='پلاک خودرو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.contractor', verbose_name='پیمانکار')),
            ],
        ),
        migrations.CreateModel(
            name='MiningMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('Loader', 'بارکننده'), ('Transporter', 'حمل کننده'), ('RoadBuilder', 'جاده سازی')], max_length=20, verbose_name='نوع دستگاه')),
                ('machine_name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('workshop_code', models.CharField(max_length=20, verbose_name='کد کارگاهی')),
                ('ownership', models.CharField(choices=[('Company', 'شرکت'), ('Contractor', 'پیمانکار')], max_length=10, verbose_name='مالکیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('contractor', models.ForeignKey(blank=True, help_text='در صورت مالکیت پیمانکار، پیمانکار را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.contractor', verbose_name='پیمانکار')),
            ],
        ),
    ]
