# Generated by Django 5.1.2 on 2024-10-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0002_alter_contractor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningblock',
            name='type',
            field=models.CharField(choices=[('w', 'باطله'), ('o', 'سنگ پرعیار'), ('w&o', 'ترکیبی')], default='w', max_length=20, verbose_name='نوع بلوک سنگ'),
        ),
        migrations.AlterField(
            model_name='miningmachine',
            name='machine_type',
            field=models.CharField(choices=[('Loader', 'بارکننده'), ('Transporter', 'حمل کننده'), ('RoadBuilder', 'جاده سازی'), ('Driller', 'حفاری')], max_length=20, verbose_name='نوع دستگاه'),
        ),
    ]
