# Generated by Django 5.1.2 on 2024-11-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0003_alter_miningblock_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorvehicle',
            name='number_car',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره خودرو'),
        ),
        migrations.AlterField(
            model_name='contractorvehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('pickup truck', 'وانت'), ('riding', 'سواری'), ('bus', 'اتوبوس'), ('minibus', 'مینی بوس'), ('van', 'ون')], max_length=50, verbose_name='نوع خودرو'),
        ),
    ]
