# Generated by Django 5.1.2 on 2024-11-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0004_contractorvehicle_number_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorvehicle',
            name='ownership',
            field=models.CharField(blank=True, choices=[('Company', 'شرکت'), ('Contractor', 'پیمانکار')], max_length=10, null=True, verbose_name='مالکیت'),
        ),
        migrations.AlterField(
            model_name='contractorvehicle',
            name='contractor',
            field=models.ForeignKey(blank=True, help_text='در صورت مالکیت پیمانکار، پیمانکار را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.contractor', verbose_name='پیمانکار'),
        ),
    ]
