# Generated by Django 5.1.2 on 2024-11-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0005_contractorvehicle_ownership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryWorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گروه کاری',
                'verbose_name_plural': 'گروه\u200cهای کاری',
            },
        ),
        migrations.CreateModel(
            name='TypeMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع دستگاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع دستگاه',
                'verbose_name_plural': 'نوع های دستگاه',
            },
        ),
        migrations.RemoveField(
            model_name='miningmachine',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='miningmachine',
            name='machine_name',
        ),
        migrations.AlterField(
            model_name='miningmachine',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.contractor', verbose_name='مالکیت'),
        ),
        migrations.AddField(
            model_name='miningmachine',
            name='machine_workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.machineryworkgroup', verbose_name='گروه کاری'),
        ),
        migrations.AlterField(
            model_name='miningmachine',
            name='machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.typemachine', verbose_name='نوع دستگاه'),
        ),
    ]
