# Generated by Django 5.1.2 on 2024-11-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0006_machineryworkgroup_typemachine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemachine',
            name='machine_workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.machineryworkgroup', verbose_name='گروه کاری'),
        ),
    ]
