# Generated by Django 5.1.2 on 2024-12-06 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0007_typemachine_machine_workgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سنگ معدنی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع سنگ معدنی',
                'verbose_name_plural': 'انواع سنگ\u200cهای معدنی',
            },
        ),
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dump_name', models.CharField(max_length=100, verbose_name='نام دمپ')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='موقعیت دمپ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('mineral_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.mineraltype', verbose_name='نوع سنگ معدنی')),
            ],
            options={
                'verbose_name': 'دمپ',
                'verbose_name_plural': 'دمپ\u200cها',
            },
        ),
    ]
