# Generated by Django 5.1.2 on 2024-12-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0008_mineraltype_dump'),
        ('contractor_management', '0005_alter_vehicle_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningmachine',
            name='ownership',
            field=models.ForeignKey(blank=True, default='شرکت', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractor_management.contractor', verbose_name='مالکیت'),
        ),
        migrations.DeleteModel(
            name='ContractorVehicle',
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
