# Generated by Django 5.1.2 on 2024-12-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0010_alter_miningmachine_ownership'),
        ('contractor_management', '0005_alter_vehicle_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningmachine',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractor_management.contractor', verbose_name='پیمانکار'),
        ),
        migrations.AlterField(
            model_name='miningmachine',
            name='ownership',
            field=models.CharField(choices=[('Company', 'شرکت'), ('Contractor', 'پیمانکار')], default='Company', max_length=10, verbose_name='مالکیت'),
        ),
    ]
