# Generated by Django 5.1.2 on 2025-03-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0011_miningmachine_contractor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('fire_truck', 'خودروی آتش\u200cنشانی'), ('ambulance', 'آمبولانس'), ('rescue', 'خودروی امداد و نجات')], max_length=20, verbose_name='نوع خودرو')),
                ('workshop_code', models.CharField(max_length=20, unique=True, verbose_name='کد کارگاهی')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='شماره پلاک')),
                ('model', models.CharField(max_length=100, verbose_name='مدل خودرو')),
                ('manufacture_year', models.IntegerField(verbose_name='سال ساخت')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('maintenance', 'در حال تعمیر')], default='active', max_length=20, verbose_name='وضعیت')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین سرویس')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سرویس بعدی')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای بیمه')),
                ('technical_inspection_expiry', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای معاینه فنی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'خودروی امدادی',
                'verbose_name_plural': 'خودروهای امدادی',
            },
        ),
    ]
