# Generated by Django 5.1.2 on 2024-12-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0011_miningmachine_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningblock',
            name='type',
            field=models.ForeignKey(blank=True, default='w', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseInfo.mineraltype', verbose_name='نوع بلوک سنگ'),
        ),
    ]
