# Generated by Django 5.1.2 on 2025-04-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0012_emergencyvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyvehicle',
            name='has_brake',
            field=models.BooleanField(default=True, verbose_name='دارای سیستم ترمز'),
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='has_equipment',
            field=models.BooleanField(default=True, verbose_name='دارای تجهیزات آتش\u200cنشانی'),
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='has_extinguisher',
            field=models.BooleanField(default=True, verbose_name='دارای خاموش\u200cکننده دستی'),
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='has_foam',
            field=models.BooleanField(default=True, verbose_name='دارای پودر و فوم'),
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='has_horn',
            field=models.BooleanField(default=True, verbose_name='دارای بوق و چراغ گردان'),
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='has_hose',
            field=models.BooleanField(default=True, verbose_name='دارای شیلنگ و اتصالات'),
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='has_lighting',
            field=models.BooleanField(default=True, verbose_name='دارای سیستم روشنایی'),
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='has_monitor',
            field=models.BooleanField(default=True, verbose_name='دارای مانیتور'),
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='has_tire',
            field=models.BooleanField(default=True, verbose_name='دارای لاستیک'),
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='has_water',
            field=models.BooleanField(default=True, verbose_name='دارای آب'),
        ),
    ]
