# Generated by Django 5.1.2 on 2024-10-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsShiftReports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftreport',
            options={'verbose_name': 'گزارش شیفت', 'verbose_name_plural': 'گزارشات شیفت'},
        ),
        migrations.RemoveField(
            model_name='shiftreport',
            name='mining_machine_reports',
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='group',
            field=models.CharField(choices=[('A', 'گروه A'), ('B', 'گروه B'), ('C', 'گروه C'), ('D', 'گروه D'), ('G', 'گروه G')], default=1, max_length=1, verbose_name='گروه کاری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='loading_operations',
            field=models.ManyToManyField(blank=True, related_name='shift_reports', to='OperationsShiftReports.loadingoperation'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_date',
            field=models.DateField(verbose_name='تاریخ شیفت'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_leaves',
            field=models.ManyToManyField(blank=True, related_name='shift_reports', to='OperationsShiftReports.shiftleave'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='supervisor_comments',
            field=models.TextField(blank=True, verbose_name='توضیحات سرشیفت'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='vehicle_reports',
            field=models.ManyToManyField(blank=True, related_name='shift_reports', to='OperationsShiftReports.vehiclereport'),
        ),
    ]
