# Generated by Django 5.1.2 on 2024-10-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsShiftReports', '0003_alter_shiftleave_personnel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='attached_file',
            field=models.FileField(blank=True, upload_to='shift_reports', verbose_name='فایل ضمیمه'),
        ),
    ]
