# Generated by Django 5.1.2 on 2024-10-29 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsShiftReports', '0005_alter_shiftreport_attached_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_reports', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
    ]
