# Generated by Django 5.1.2 on 2024-10-29 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsShiftReports', '0006_shiftreport_creator'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftreport',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_reports', to='accounts.userprofile', verbose_name='ایجاد کننده'),
        ),
    ]
