# Generated by Django 5.1.2 on 2024-10-30 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0003_alter_miningblock_type_and_more'),
        ('OperationsShiftReports', '0007_alter_shiftreport_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=20, verbose_name='وضعیت')),
                ('inactive_reason', models.TextField(blank=True, null=True, verbose_name='دلیل غیرفعال بودن')),
                ('block', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.miningblock', verbose_name='بلوک')),
                ('loader', models.ForeignKey(limit_choices_to={'is_active': True, 'machine_type': 'Loader'}, on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.miningmachine', verbose_name='بارکننده')),
            ],
            options={
                'verbose_name': 'وضعیت بارکننده',
                'verbose_name_plural': 'وضعیت بارکننده\u200cها',
            },
        ),
        migrations.DeleteModel(
            name='MiningMachineReport',
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='loader_statuses',
            field=models.ManyToManyField(blank=True, related_name='shift_reports', to='OperationsShiftReports.loaderstatus'),
        ),
    ]
