# Generated by Django 5.1.2 on 2024-11-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsShiftReports', '0008_loaderstatus_delete_miningmachinereport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingoperation',
            name='stone_type',
            field=models.CharField(choices=[('w', 'باطله'), ('O', 'آهن'), ('T', 'T1')], default='w', max_length=50, verbose_name='نوع سنگ'),
        ),
    ]
