# Generated by Django 5.1.2 on 2024-12-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsShiftReports', '0010_remove_shiftreport_shift_leaves_delete_shiftleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftreport',
            name='vehicle_reports',
        ),
        migrations.DeleteModel(
            name='VehicleReport',
        ),
    ]
