# Generated by Django 5.1.2 on 2024-12-06 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsShiftReports', '0011_remove_shiftreport_vehicle_reports_and_more'),
        ('accounts', '0006_alter_userprofile_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100, verbose_name='نام خودرو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('inactive_time_start', models.TimeField(blank=True, null=True, verbose_name='زمان شروع غیر فعال بودن')),
                ('inactive_time_end', models.TimeField(blank=True, null=True, verbose_name='زمان پایان غیر فعال بودن')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_status', models.CharField(choices=[('authorized', 'مجاز'), ('unauthorized', 'غیر مجاز')], default='unauthorized', max_length=50, verbose_name='وضعیت مرخصی')),
                ('personnel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='shift_leaves',
            field=models.ManyToManyField(blank=True, related_name='shift_reports', to='OperationsShiftReports.shiftleave'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='vehicle_reports',
            field=models.ManyToManyField(blank=True, related_name='shift_reports', to='OperationsShiftReports.vehiclereport'),
        ),
    ]
