# Generated by Django 5.1.2 on 2025-01-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsShiftReports', '0012_vehiclereport_shiftleave_shiftreport_shift_leaves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftreport',
            name='group',
            field=models.CharField(choices=[('A', 'گروه A'), ('B', 'گروه B'), ('C', 'گروه C'), ('D', 'گروه D'), ('G', 'گروه G'), ('G2', 'گروه G2')], max_length=2, verbose_name='گروه کاری'),
        ),
    ]
