# Generated by Django 5.1.4 on 2025-10-28 20:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsShiftReports', '0013_alter_shiftreport_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftreport',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='shift_reports/%Y/%m/%d/', validators=[core.validators.validate_document_file], verbose_name='فایل ضمیمه'),
        ),
    ]
