# Generated by Django 5.1.2 on 2024-12-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='hse_plan_file',
            field=models.FileField(blank=True, null=True, upload_to='hse_plans/', verbose_name='طرح ایمنی، بهداشت و محیط زیست'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='hse_plan',
            field=models.BooleanField(default=False, verbose_name='طرح ایمنی، بهداشت و محیط زیست'),
        ),
    ]
