# Generated by Django 5.1.2 on 2024-12-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0002_contractor_hse_plan_file_alter_contractor_hse_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='number_of_insurance',
            field=models.CharField(default=222222, max_length=255, verbose_name='شماره بیمه تامین اجتماعی'),
            preserve_default=False,
        ),
    ]
