# Generated by Django 5.1.2 on 2024-12-07 14:01

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0003_employee_number_of_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='fire_insurance_expiry',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انقضای بیمه آتش\u200cسوزی'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='number_of_social_insurance',
            field=models.CharField(default=11111, max_length=255, verbose_name='شماره بیمه تامین اجتماعی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='card_national_img',
            field=models.FileField(blank=True, null=True, upload_to='card_national_imgs/', verbose_name='تصویر کارت ملی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='certificate_img',
            field=models.FileField(blank=True, null=True, upload_to='certificate_national_imgs/', verbose_name='تصویر شناسنامه'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد کارگاهی خودرو'),
        ),
    ]
