# Generated by Django 5.1.2 on 2024-12-07 17:49

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0004_contractor_fire_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_expiry',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انقضای بیمه\u200cنامه'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='permit_expiry',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انقضای آخرین مجوز خودرو'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='technical_inspection_expiry',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انقضای معاینه فنی'),
        ),
    ]
