# Generated by Django 5.1.2 on 2024-12-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='group',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='گروه کاری'),
        ),
        migrations.AddField(
            model_name='report',
            name='shift',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شیفت کاری'),
        ),
    ]
