# Generated by Django 5.1.2 on 2024-12-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0006_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='restart_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='stop_active',
        ),
        migrations.RemoveField(
            model_name='report',
            name='stop_time',
        ),
        migrations.AddField(
            model_name='report',
            name='stop_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت پایان توقف'),
        ),
        migrations.AddField(
            model_name='report',
            name='stop_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت شروع توقف'),
        ),
    ]
