# Generated by Django 5.1.2 on 2025-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0008_alter_report_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.CharField(choices=[('mining', 'ماشین آلات معدنی'), ('light', 'خودروهای سبک')], default='light', max_length=10, verbose_name='دسته\u200cبندی خودرو'),
        ),
    ]
