# Generated by Django 5.1.2 on 2025-04-22 14:55

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0009_vehicle_vehicle_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ گزارش'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('vehicle', 'report_date', 'shift')},
        ),
    ]
