# Generated by Django 5.1.2 on 2025-04-22 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0011_alter_report_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('vehicle', 'report_date', 'shift', 'user')},
        ),
    ]
