# Generated by Django 5.1.2 on 2025-05-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0012_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.CharField(choices=[('mining', 'ماشین آلات معدنی'), ('light', 'خودروهای سبک'), ('transportation', 'حمل و نقل')], default='light', max_length=15, verbose_name='دسته\u200cبندی خودرو'),
        ),
    ]
