# Generated by Django 5.1.4 on 2025-10-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0013_alter_vehicle_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contractor_certificate_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای صلاحیت پیمانکاری'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='fire_insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای بیمه آتش\u200cسوزی'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='liability_insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای بیمه مسئولیت مدنی'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='safety_certificate_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای صلاحیت ایمنی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='entry_permit_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای مجوز ورود'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ گزارش'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ثبت گزارش'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای بیمه\u200cنامه'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='permit_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای آخرین مجوز خودرو'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='technical_inspection_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای معاینه فنی'),
        ),
    ]
