# Generated by Django 5.1.4 on 2025-10-30 19:16

from django.db import migrations, transaction


def populate_report_date(apps, schema_editor):
    """پر کردن فیلد report_date از report_datetime برای گزارش‌های موجود"""
    Report = apps.get_model('contractor_management', 'Report')
    
    # شناسایی و حذف گزارش‌های تکراری قبل از تنظیم report_date
    from collections import defaultdict
    
    duplicates_to_delete = []
    seen = defaultdict(list)
    
    # گروه‌بندی گزارش‌ها بر اساس unique_together fields
    for report in Report.objects.filter(report_date__isnull=True).order_by('id'):
        if report.report_datetime:
            date_only = report.report_datetime.date()
            key = (report.vehicle_id, date_only, report.shift, report.user_id)
            seen[key].append(report)
    
    # حذف گزارش‌های تکراری (نگه داشتن اولین گزارش)
    for key, reports in seen.items():
        if len(reports) > 1:
            # نگه داشتن اولین گزارش و حذف بقیه
            for report in reports[1:]:
                print(f"Deleting duplicate report ID: {report.id}")
                duplicates_to_delete.append(report.id)
    
    # حذف گزارش‌های تکراری
    if duplicates_to_delete:
        Report.objects.filter(id__in=duplicates_to_delete).delete()
        print(f"Deleted {len(duplicates_to_delete)} duplicate reports")
    
    # حالا به‌روزرسانی report_date برای گزارش‌های باقی‌مانده
    for report in Report.objects.filter(report_date__isnull=True):
        if report.report_datetime:
            report.report_date = report.report_datetime.date()
            report.save(update_fields=['report_date'])


def reverse_populate_report_date(apps, schema_editor):
    """عملیات معکوس - در صورت نیاز به بازگشت"""
    # نیازی به عملیات معکوس نیست
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_management', '0014_alter_contractor_contractor_certificate_expiry_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_report_date, reverse_populate_report_date),
    ]
