# Generated by Django 4.2.30 on 2026-08-24 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave_reports', '0014_leavesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('replacement', 'جانشین'), ('manager', 'مدیر تأییدکننده')], max_length=12)),
                ('target', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('skipped_no_phone', 'بدون شماره همراه'), ('skipped_duplicate', 'اخیراً ارسال شده')], max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='leave_reports.shiftreport')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ یادآوری',
                'verbose_name_plural': 'لاگ\u200cهای یادآوری',
                'ordering': ('-created_at',),
            },
        ),
    ]
