# Generated by Django 4.2.30 on 2026-08-24 14:44

from django.db import migrations, models
import message_center.models


class Migration(migrations.Migration):

    dependencies = [
        ('message_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_phone', models.CharField(blank=True, default='', max_length=20)),
                ('chat_guid', models.CharField(blank=True, default='', max_length=40)),
                ('author_guid', models.CharField(blank=True, default='', max_length=40)),
                ('message_type', models.CharField(blank=True, default='', max_length=30)),
                ('text', models.TextField(blank=True, default='')),
                ('message_id', models.CharField(blank=True, default='', max_length=64)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیام دریافتی',
                'verbose_name_plural': 'پیام\u200cهای دریافتی',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default=message_center.models.generate_webhook_secret, max_length=100, verbose_name='کد امنیتی')),
                ('is_active', models.BooleanField(default=True, verbose_name='دریافت فعال باشد')),
                ('last_received_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین دریافت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'تنظیمات وب\u200cهوک پیام',
                'verbose_name_plural': 'تنظیمات وب\u200cهوک پیام',
            },
        ),
    ]
