# Generated by Django 4.2.30 on 2026-08-27 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message_center', '0002_inboundmessage_webhookconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان پیام')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('channel', models.CharField(choices=[('sms', 'پیامک (SMS)'), ('rubika', 'روبیکا')], default='sms', max_length=10, verbose_name='کانال ارسال')),
                ('mobile_numbers', models.JSONField(blank=True, default=list, verbose_name='شماره\u200cهای موبایل')),
                ('personnel_codes', models.JSONField(blank=True, default=list, verbose_name='کدهای پرسنلی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('resolved', 'آماده ارسال'), ('scheduled', 'زمان\u200cبندی شده'), ('sending', 'در حال ارسال'), ('completed', 'انجام شد'), ('partial', 'با خطا انجام شد'), ('failed', 'ناموفق'), ('cancelled', 'لغو شد')], default='draft', max_length=12, verbose_name='وضعیت')),
                ('recipients_total', models.PositiveIntegerField(default=0, verbose_name='دریافت\u200cکنندگان کل')),
                ('recipients_resolved', models.PositiveIntegerField(default=0, verbose_name='دریافت\u200cکنندگان قابل ارسال')),
                ('recipients_invalid', models.PositiveIntegerField(default=0, verbose_name='دریافت\u200cکنندگان نامعتبر')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='زمان\u200cبندی ارسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('source_file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='نام فایل منبع')),
                ('error', models.TextField(blank=True, default='', verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام گروهی',
                'verbose_name_plural': 'پیام\u200cهای گروهی',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان قالب')),
                ('text', models.TextField(verbose_name='متن قالب')),
                ('channel', models.CharField(choices=[('sms', 'پیامک (SMS)'), ('rubika', 'روبیکا')], default='sms', max_length=10, verbose_name='کانال ارسال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قالب پیام',
                'verbose_name_plural': 'قالب\u200cهای پیام',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, default='', max_length=30, verbose_name='شماره موبایل')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='نام')),
                ('resolve_status', models.CharField(choices=[('ok', 'یافت شد'), ('no_phone', 'بدون شماره همراه'), ('not_found', 'کاربر یافت نشد'), ('invalid', 'شماره نامعتبر')], default='ok', max_length=15, verbose_name='وضعیت تشخیص')),
                ('resolve_note', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح تشخیص')),
                ('send_status', models.CharField(choices=[('pending', 'در انتظار'), ('sending', 'در حال ارسال'), ('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('canceled', 'لغو شد')], default='pending', max_length=12, verbose_name='وضعیت ارسال')),
                ('error', models.TextField(blank=True, default='', verbose_name='خطای ارسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='message_center.broadcast')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'گیرنده پیام گروهی',
                'verbose_name_plural': 'گیرندگان پیام گروهی',
            },
        ),
    ]
