# Generated by Django 4.2 on 2025-11-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anomalis', '0006_comment_file_alter_comment_comment'),
        ('hse_incidents', '0007_remove_hsecompletionreport_patient_condition_on_dispatch_and_more'),
        ('accounts', '0014_userprofile_national_code_alter_payslip_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_source', models.CharField(choices=[('site_visit', 'بازدیدهای میدانی و آنومالی ریپورت'), ('consultation', 'مشارکت و مشاوره کارکنان'), ('audit', 'نتایج ممیزی\u200cها'), ('incidents', 'حوادث و شبه حوادث'), ('changes', 'تغییرات'), ('physical', 'عوامل فیزیکی'), ('chemical', 'عوامل شیمیایی'), ('biological', 'عوامل محیط زیستی و بیولوژیکی'), ('ergonomic', 'عوامل ارگونومیک و انسانی'), ('activities', 'فعالیت\u200cها و عملیات کاری'), ('energy', 'انرژی\u200cهای خطرناک'), ('environmental', 'وضعیت\u200cهای محیطی'), ('other', 'سایر')], max_length=50, verbose_name='منشا شناسایی ریسک')),
                ('risk_source_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='سایر منشاها (در صورت انتخاب سایر)')),
                ('activity_component', models.CharField(max_length=255, verbose_name='اجزا شغل/فعالیت/تجهیز')),
                ('is_routine', models.BooleanField(default=True, verbose_name='روتین است؟')),
                ('potential_event', models.CharField(help_text='چه اتفاقی ممکن است بیفتد', max_length=255, verbose_name='رویداد محتمل')),
                ('causes', models.TextField(help_text='چرا این رویداد ممکن است رخ دهد', verbose_name='علل احتمالی وقوع')),
                ('existing_controls', models.TextField(help_text='اقدامات کنترلی که در حال حاضر اجرا می\u200cشود', verbose_name='کنترل\u200cهای موجود')),
                ('control_failure_causes', models.TextField(help_text='چرا کنترل\u200cهای فعلی ممکن است ناکام بمانند', verbose_name='علل احتمالی شکست کنترل\u200cها')),
                ('has_legal_requirement', models.BooleanField(default=False, verbose_name='الزام قانونی دارد؟')),
                ('legal_requirement_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح الزام قانونی')),
                ('is_legal_compliant', models.BooleanField(blank=True, null=True, verbose_name='رعایت شده است؟')),
                ('probability', models.IntegerField(choices=[(1, '1 - خیلی کم (کمتر از یک بار در ۵ سال)'), (2, '2 - کم (۵ سال یکبار)'), (3, '3 - متوسط (وقوع سالیانه)'), (4, '4 - زیاد (چند بار در سال)'), (5, '5 - خیلی زیاد (چند بار در ماه)')], verbose_name='احتمال وقوع (P)')),
                ('severity', models.IntegerField(choices=[(1, '1 - آسیب جزئی (بدون استراحت)'), (2, '2 - آسیب شدید (1 تا 14 روز استراحت)'), (3, '3 - آسیب خیلی شدید (قطع عضو/بیش از 15 روز)'), (4, '4 - ناتوانی و از کار افتادگی دائم'), (5, '5 - مرگ')], verbose_name='شدت پیامد (S)')),
                ('risk_number', models.IntegerField(editable=False, verbose_name='عدد ریسک (RPN = P × S)')),
                ('risk_level', models.CharField(choices=[('Low', 'پایین (سبز) - قابل پذیرش'), ('Medium', 'متوسط (زرد) - نیاز به کاهش'), ('High', 'بالا (قرمز) - غیرقابل پذیرش')], editable=False, max_length=20, verbose_name='سطح ریسک')),
                ('control_elimination', models.TextField(blank=True, help_text='حذف کامل خطر از محیط کار', verbose_name='1. حذف خطر (Elimination)')),
                ('control_substitution', models.TextField(blank=True, help_text='جایگزین کردن با چیز کم\u200cخطرتر', verbose_name='2. جایگزینی (Substitution)')),
                ('control_engineering', models.TextField(blank=True, help_text='کنترل\u200cهای فنی و مهندسی', verbose_name='3. کنترل مهندسی (Engineering)')),
                ('control_admin', models.TextField(blank=True, help_text='دستورالعمل\u200cها، آموزش، تابلوها', verbose_name='4. کنترل اداری (Administrative)')),
                ('control_ppe', models.TextField(blank=True, help_text='تجهیزات حفاظت شخصی', verbose_name='5. لوازم حفاظت فردی (PPE)')),
                ('corrective_action_required', models.BooleanField(default=False, verbose_name='نیاز به اقدام اصلاحی دارد؟')),
                ('action_number', models.CharField(blank=True, help_text='شماره اقدام اصلاحی در سیستم', max_length=50, verbose_name='شماره اقدام')),
                ('action_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اقدام')),
                ('action_deadline', models.DateField(blank=True, null=True, verbose_name='مهلت اقدام')),
                ('is_mue', models.BooleanField(default=False, help_text='آیا این ریسک می\u200cتواند به وضعیت غیرقابل پذیرش تبدیل شود؟', verbose_name='قابلیت تبدیل به MUE (Unacceptable)')),
                ('mue_code', models.CharField(blank=True, max_length=50, verbose_name='کد MUE')),
                ('is_emergency', models.BooleanField(default=False, help_text='آیا می\u200cتواند منجر به شرایط اضطراری شود؟', verbose_name='قابلیت تبدیل به شرایط اضطراری')),
                ('emergency_code', models.CharField(blank=True, max_length=50, verbose_name='کد شرایط اضطراری')),
                ('re_evaluation_date', models.DateField(blank=True, null=True, verbose_name='تاریخ محاسبه مجدد')),
                ('residual_probability', models.IntegerField(blank=True, choices=[(1, '1 - خیلی کم (کمتر از یک بار در ۵ سال)'), (2, '2 - کم (۵ سال یکبار)'), (3, '3 - متوسط (وقوع سالیانه)'), (4, '4 - زیاد (چند بار در سال)'), (5, '5 - خیلی زیاد (چند بار در ماه)')], null=True, verbose_name='احتمال مجدد (پس از اقدامات)')),
                ('residual_severity', models.IntegerField(blank=True, choices=[(1, '1 - آسیب جزئی (بدون استراحت)'), (2, '2 - آسیب شدید (1 تا 14 روز استراحت)'), (3, '3 - آسیب خیلی شدید (قطع عضو/بیش از 15 روز)'), (4, '4 - ناتوانی و از کار افتادگی دائم'), (5, '5 - مرگ')], null=True, verbose_name='شدت مجدد (پس از اقدامات)')),
                ('residual_risk_number', models.IntegerField(blank=True, editable=False, null=True, verbose_name='عدد ریسک باقی\u200cمانده')),
                ('residual_risk_level', models.CharField(blank=True, choices=[('Low', 'پایین (سبز) - قابل پذیرش'), ('Medium', 'متوسط (زرد) - نیاز به کاهش'), ('High', 'بالا (قرمز) - غیرقابل پذیرش')], editable=False, max_length=20, null=True, verbose_name='سطح ریسک باقی\u200cمانده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('consequence', models.ForeignKey(help_text='نوع آسیب یا صدمه احتمالی', on_delete=django.db.models.deletion.PROTECT, to='hse_incidents.injurytype', verbose_name='شرح پیامد احتمالی (نوع آسیب)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to='accounts.userprofile', verbose_name='ایجاد شده توسط')),
                ('hazard', models.ForeignKey(help_text='نوع خطری که شناسایی شده است', on_delete=django.db.models.deletion.PROTECT, to='anomalis.anomalydescription', verbose_name='خطر (منبع آسیب)')),
                ('people_at_risk', models.ManyToManyField(help_text='سمت\u200cهایی که در معرض این خطر هستند', related_name='risks_exposed_to', to='accounts.position', verbose_name='افراد در معرض خطر')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='accounts.position', verbose_name='شغل/سمت')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_risks', to='accounts.userprofile', verbose_name='مسئول اجرا')),
            ],
            options={
                'verbose_name': 'ارزیابی ریسک',
                'verbose_name_plural': 'ارزیابی\u200cهای ریسک',
                'ordering': ['-created_at', '-risk_number'],
            },
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['position', 'risk_level'], name='risk_assess_positio_348904_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['risk_number'], name='risk_assess_risk_nu_61cbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['created_at'], name='risk_assess_created_5dd1ed_idx'),
        ),
    ]
