# Generated by Django 4.2 on 2025-11-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_national_code_alter_payslip_file'),
        ('risk_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='related_positions',
            field=models.ManyToManyField(blank=True, help_text='در صورت مشترک بودن این ریسک در چند شغل دیگر انتخاب کنید', related_name='shared_risks', to='accounts.position', verbose_name='مشاغل مشترک'),
        ),
        migrations.CreateModel(
            name='RiskAssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('initial', 'ایجاد اولیه'), ('update', 'بروزرسانی'), ('reevaluation', 'ارزیابی مجدد')], max_length=20, verbose_name='نوع تغییر')),
                ('probability', models.IntegerField(verbose_name='احتمال')),
                ('severity', models.IntegerField(verbose_name='شدت')),
                ('risk_number', models.IntegerField(verbose_name='عدد ریسک')),
                ('risk_level', models.CharField(max_length=20, verbose_name='سطح ریسک')),
                ('residual_probability', models.IntegerField(blank=True, null=True, verbose_name='احتمال باقی\u200cمانده')),
                ('residual_severity', models.IntegerField(blank=True, null=True, verbose_name='شدت باقی\u200cمانده')),
                ('residual_risk_number', models.IntegerField(blank=True, null=True, verbose_name='عدد ریسک باقی\u200cمانده')),
                ('residual_risk_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='سطح ریسک باقی\u200cمانده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='risk_assessment.riskassessment', verbose_name='ریسک')),
            ],
            options={
                'verbose_name': 'سطر تاریخچه ریسک',
                'verbose_name_plural': 'تاریخچه ارزیابی\u200cهای ریسک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان فعالیت/جزء')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to='accounts.position', verbose_name='شغل مرتبط')),
            ],
            options={
                'verbose_name': 'جزء فعالیت شغل',
                'verbose_name_plural': 'اجزای فعالیت مشاغل',
                'ordering': ['position', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='job_tasks',
            field=models.ManyToManyField(blank=True, help_text='از بین اجزای ثبت\u200cشده برای شغل، موارد مرتبط با این ریسک را انتخاب کنید', related_name='risks', to='risk_assessment.jobtask', verbose_name='اجزای فعالیت انتخابی'),
        ),
        migrations.AddIndex(
            model_name='riskassessmenthistory',
            index=models.Index(fields=['risk', 'created_at'], name='risk_assess_risk_id_8e9f84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobtask',
            unique_together={('position', 'name')},
        ),
    ]
