# Generated by Django 4.2 on 2025-11-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_national_code_alter_payslip_file'),
        ('risk_assessment', '0002_riskassessment_related_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='people_at_risk',
            field=models.ManyToManyField(blank=True, help_text='سمت\u200cهایی که در معرض این خطر هستند', related_name='risks_exposed_to', to='accounts.position', verbose_name='افراد در معرض خطر'),
        ),
    ]
