# Generated by Django 4.2 on 2025-11-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_national_code_alter_payslip_file'),
        ('risk_assessment', '0004_remove_riskassessment_job_tasks_and_related_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت تأیید'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_risks', to='accounts.userprofile', verbose_name='تأیید شده توسط'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ رد'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_risks', to='accounts.userprofile', verbose_name='رد شده توسط'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='در صورت رد ریسک، دلیل آن را ذکر کنید', verbose_name='دلیل رد'),
        ),
    ]
