# Generated by Django 5.1.2 on 2024-11-29 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_unit'),
        ('leave_reports', '0002_shiftreport_created_at_shiftreport_work_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='crate_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
    ]
