# Generated by Django 5.1.2 on 2025-01-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_reports', '0004_alter_shiftreport_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='leave_type',
            field=models.CharField(choices=[('regular', 'مرخصی'), ('absence', 'غیبت'), ('hourly', 'مرخصی ساعتی'), ('sick_leave', 'مرخصی استعلاجی')], max_length=10),
        ),
    ]
