# Generated by Django 5.1.2 on 2025-03-17 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_reports', '0005_shiftreport_description_alter_shiftreport_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='work_group',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
