# Generated by Django 5.1.2 on 2025-03-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_reports', '0006_alter_shiftreport_shift_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='shift_type',
            field=models.CharField(choices=[('day', 'روزکاراول'), ('day2', 'روزکاردوم'), ('evening', 'عصرکاراول'), ('evening2', 'عصرکاردوم'), ('night', 'شبکاراول'), ('night2', 'شبکاردوم')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_date',
            field=models.DateField(db_index=True),
        ),
    ]
