# Generated by Django 5.1.2 on 2025-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_reports', '0007_shiftreport_shift_type_alter_shiftreport_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='exported_to_excel',
            field=models.BooleanField(default=False, verbose_name='خروجی اکسل گرفته شده'),
        ),
    ]
