# Generated by Django 5.1.2 on 2025-04-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_reports', '0008_shiftreport_exported_to_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftreport',
            name='status',
            field=models.BooleanField(choices=[(True, 'ثبت شده'), (False, 'ثبت نشده')], default=False, verbose_name='وضعیت ثبت'),
        ),
    ]
