# Generated by Django 5.2.4 on 2025-11-05 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_driverlicense_back_image_and_more'),
        ('leave_reports', '0009_shiftreport_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست مرخصی', 'verbose_name_plural': 'درخواست\u200cهای مرخصی'},
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید نهایی'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='final_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='accounts.userprofile', verbose_name='تأیید کننده نهایی'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ رد'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_leaves', to=settings.AUTH_USER_MODEL, verbose_name='رد کننده'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='replacement_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید جایگزین'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='replacement_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید جایگزین'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='replacement_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_requests', to=settings.AUTH_USER_MODEL, verbose_name='جایگزین پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='crate_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leaves', to='accounts.userprofile', verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='leave_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='ساعات مرخصی'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='leave_type',
            field=models.CharField(choices=[('regular', 'مرخصی استحقاقی'), ('absence', 'غیبت'), ('hourly', 'مرخصی ساعتی'), ('sick_leave', 'مرخصی استعلاجی')], max_length=15, verbose_name='نوع مرخصی'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_date',
            field=models.DateField(db_index=True, verbose_name='تاریخ مرخصی'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_type',
            field=models.CharField(choices=[('day', 'روزکار اول'), ('day2', 'روزکار دوم'), ('evening', 'عصرکار اول'), ('evening2', 'عصرکار دوم'), ('night', 'شبکار اول'), ('night2', 'شبکار دوم')], max_length=10, verbose_name='نوع شیفت'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='status',
            field=models.CharField(choices=[('pending_replacement', 'در انتظار تأیید جایگزین'), ('pending_approval', 'در انتظار تأیید مدیر'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending_replacement', max_length=25, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست دهنده'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='work_group',
            field=models.CharField(db_index=True, max_length=100, verbose_name='گروه کاری'),
        ),
        migrations.CreateModel(
            name='ApprovalHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='تأیید کننده')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.part', verbose_name='قسمت')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.section', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'سلسله مراتب تأیید',
                'verbose_name_plural': 'سلسله مراتب تأیید',
                'unique_together': {('section', 'part')},
            },
        ),
    ]
