# Generated by Django 5.1.2 on 2025-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_reports', '0009_alter_shiftreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='registration',
            field=models.BooleanField(choices=[(True, 'ثبت شده'), (False, 'ثبت نشده')], default=False, verbose_name='وضعیت ثبت'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='status',
            field=models.CharField(default='reported', max_length=10),
        ),
    ]
