# Generated by Django 5.2.4 on 2025-11-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_reports', '0010_alter_shiftreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='medical_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_medical_docs/', verbose_name='مدارک پزشکی'),
        ),
    ]
