# Generated by Django 4.2 on 2025-11-24 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_national_code_alter_payslip_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_reports', '0011_shiftreport_medical_document'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvalhierarchy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvalhierarchy',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.position', verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='approvalhierarchy',
            name='specific_user',
            field=models.ForeignKey(blank=True, help_text='برای تعریف تأیید کننده خاص برای یک کاربر مشخص', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر خاص'),
        ),
        migrations.AddField(
            model_name='approvalhierarchy',
            name='unit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.unitgroup', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='approvalhierarchy',
            name='work_group',
            field=models.CharField(blank=True, choices=[('A', 'گروه A'), ('B', 'گروه B'), ('C', 'گروه C'), ('D', 'گروه D'), ('G', 'گروه G'), ('G2', 'گروه G2')], max_length=2, null=True, verbose_name='گروه کاری'),
        ),
        migrations.AddIndex(
            model_name='approvalhierarchy',
            index=models.Index(fields=['work_group', 'section', 'part'], name='leave_repor_work_gr_4df23b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalhierarchy',
            index=models.Index(fields=['specific_user'], name='leave_repor_specifi_f0e434_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalhierarchy',
            index=models.Index(fields=['position', 'unit_group'], name='leave_repor_positio_8fc58f_idx'),
        ),
    ]
