# Generated by Django 4.2.30 on 2026-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_reports', '0013_change_specific_user_to_many_to_many'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_window_enabled', models.BooleanField(default=False, help_text='در صورت فعال بودن، ثبت درخواست فقط در بازه مجاز نسبت به تاریخ مرخصی امکان\u200cپذیر است.', verbose_name='محدودیت مهلت ثبت فعال باشد')),
                ('registration_max_days_after', models.PositiveSmallIntegerField(default=3, help_text='حداکثر فاصله مجاز بین تاریخ مرخصی و روز ثبت درخواست.', verbose_name='مهلت ثبت پس از تاریخ مرخصی (روز)')),
                ('registration_max_days_future', models.PositiveSmallIntegerField(default=3, help_text='درخواست برای چند روز آینده قابل ثبت است.', verbose_name='حداکثر روزهای آینده مجاز (روز)')),
                ('approval_window_enabled', models.BooleanField(default=False, help_text='در صورت فعال بودن، تأییدکننده\u200cها فقط تا N روز پس از تاریخ مرخصی فرصت تأیید دارند.', verbose_name='محدودیت مهلت تأیید فعال باشد')),
                ('approval_max_days', models.PositiveSmallIntegerField(default=3, verbose_name='مهلت تأیید پس از تاریخ مرخصی (روز)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'تنظیمات مهلت مرخصی',
                'verbose_name_plural': 'تنظیمات مهلت مرخصی',
            },
        ),
    ]
