# Generated by Django 4.2 on 2025-11-09 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import rubika_bot.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RubikaBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='توکن ربات روبیکا (به صورت رمزگذاری\u200cشده ذخیره می\u200cشود).', max_length=255, null=True, validators=[rubika_bot.validators.validate_rubika_token]))),
                ('bot_username', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rubika Bot Settings',
                'verbose_name_plural': 'Rubika Bot Settings',
            },
        ),
        migrations.CreateModel(
            name='RubikaConnectionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RubikaUser',
            fields=[
                ('chat_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('incoming', 'دریافتی'), ('outgoing', 'ارسالی'), ('error', 'خطا'), ('info', 'اطلاعات')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['created_at'], name='rubika_bot__created_6120d9_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['log_type', 'created_at'], name='rubika_bot__log_typ_f6cd02_idx'),
        ),
        migrations.AddField(
            model_name='rubikauser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubika_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubikaconnectioncode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubika_connection_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rubikauser',
            index=models.Index(fields=['first_name'], name='rubika_bot__first_n_083e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='rubikauser',
            index=models.Index(fields=['last_name'], name='rubika_bot__last_na_6b4300_idx'),
        ),
        migrations.AddIndex(
            model_name='rubikaconnectioncode',
            index=models.Index(fields=['user', 'used'], name='rubika_bot__user_id_dc6909_idx'),
        ),
    ]
