# Generated by Django 5.2.4 on 2025-11-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubika_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubikabotsettings',
            name='bot_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rubikabotsettings',
            name='deeplink_template',
            field=models.CharField(blank=True, help_text='Use {bot_username} and {code}, e.g. https://rubika.ir/{bot_username}?start={code}', max_length=255, null=True),
        ),
    ]
