# Generated by Django 4.2 on 2025-11-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubika_bot', '0003_leaverequeststate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(default='idle', help_text='مرحله فعلی: idle, national_code, personnel_code, confirm', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict, help_text='داده\u200cهای جمع\u200cآوری شده شامل: national_code, personnel_code')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'وضعیت درخواست اتصال',
                'verbose_name_plural': 'وضعیت\u200cهای درخواست اتصال',
            },
        ),
        migrations.RenameIndex(
            model_name='leaverequeststate',
            new_name='rubika_bot__rubika__09d8b3_idx',
            old_name='rubika_bot_rubika__7e8a9f_idx',
        ),
        migrations.AddField(
            model_name='connectionrequeststate',
            name='rubika_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_request_state', to='rubika_bot.rubikauser'),
        ),
        migrations.AddIndex(
            model_name='connectionrequeststate',
            index=models.Index(fields=['rubika_user', 'step'], name='rubika_bot__rubika__a02ce4_idx'),
        ),
    ]
