# Generated by Django 4.2 on 2026-08-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubika_bot', '0004_connectionrequeststate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymReferralState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(default='idle', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rubika_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_referral_state', to='rubika_bot.rubikauser')),
            ],
        ),
        migrations.AddIndex(
            model_name='gymreferralstate',
            index=models.Index(fields=['rubika_user', 'step'], name='rubika_bot__rubika__6d723f_idx'),
        ),
    ]
