"""
Django settings for HSCprojects project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import sys
from pathlib import Path
from logging.handlers import TimedRotatingFileHandler
from datetime import datetime

# Import celery schedules فقط اگر celery دسترسی داشته باشد
try:
    from celery.schedules import crontab
    CELERY_AVAILABLE = True
except ImportError:
    CELERY_AVAILABLE = False
    # برای migrations و makemigrations، crontab لازم نیست
    if not ('makemigrations' in sys.argv or 'migrate' in sys.argv):
        raise

from django.conf.locale.fa import formats as fa_formats

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ygf6#b*bj-ko2fimc)sg=u2vo6c)5a1#c5#zr=@#8&o7nd*tpt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0', 'mtorkzadeh.ir','miepcoj.ir', 'localhost', '65.109.220.72', 'testserver']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', 

    # Third-party apps
    'corsheaders',
    'crispy_forms',
    'crispy_bootstrap5',
    'jalali_date',  # Django Jalali Date package
    'django_select2',
    'import_export',
    'formtools',
    'rest_framework',
    'django_cryptography',

    # Celery related apps
    'django_celery_results',
    'django_celery_beat',

    # Your project apps
    'core',
    'permissions.apps.PermissionsConfig',
    'meetings.apps.MeetingsConfig',
    "dashboard.apps.DashboardConfig",
    "accounts.apps.AccountsConfig",
    "anomalis.apps.AnomalisConfig",
    'analytics.apps.AnalyticsConfig',
    'shift_manager.apps.ShiftManagerConfig',
    'BaseInfo.apps.BaseinfoConfig',
    'OperationsShiftReports.apps.OperationsshiftreportsConfig',
    'dailyreport_hse.apps.DailyreportHseConfig',
    'leave_reports.apps.LeaveReportsConfig',
    'contractor_management.apps.ContractorManagementConfig',
    'hse_incidents.apps.HseIncidentsConfig',
    'machine_checklist.apps.MachineChecklistConfig',
    'fire_reports.apps.FireReportsConfig',
    'checklist_app.apps.ChecklistAppConfig',
    'emergency_services.apps.EmergencyServicesConfig',
    'fire_extinguisher_management.apps.FireExtinguisherManagementConfig',
    'rubika_bot.apps.RubikaBotConfig',
    'risk_assessment.apps.RiskAssessmentConfig',
    'hse_docs.apps.HseDocsConfig',
    'corrective_actions.apps.CorrectiveActionsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'emergency_services.middleware.EmergencyPersonnelAccessMiddleware',  # محدود کردن دسترسی پرسنل اورژانس
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HSCprojects.urls'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_profile_processor',
                'analytics.context_processors.anomaly_stats_context',
                'dashboard.context_processors.notification_context_processor',
                'shift_manager.context_processors.shift_context_processor',
                'shift_manager.context_processors.shift_data_processor',
                'permissions.context_processors.permission_context',
                'core.context_processors.site_settings',
                'core.context_processors.today_jalali',
            ],
            'builtins': [
                # Make project's Jalali template filters available globally
                'checklist_app.templatetags.checklist_filters',
                # Add a small set of form helpers (add_class) so templates can
                # use the `|add_class` filter without loading extra libs.
                'core.templatetags.form_filters',
                # Permission template filters (e.g. `|check_permission`) used
                # directly in templates and smart-if expressions.
                'permissions.templatetags.permission_tags',
            ],
        },
    },
]

WSGI_APPLICATION = 'HSCprojects.wsgi.application'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Fix for naive datetime warnings
import warnings
warnings.filterwarnings(
    'ignore',
    message=r'.*received a naive datetime.*while time zone support is active.*',
    category=RuntimeWarning,
)

# برای حالت تولید (production)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# برای حالت توسعه (development) فقط زمانی که DEBUG=True است
if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/dashboard/'

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # افزایش تعداد فیلدهای مجاز
DATA_UPLOAD_MAX_NUMBER_FILES = 250  # حداکثر تعداد فایل‌ها در یک request
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# SMS settings
SMSIR_API_KEY = 'gCLhWKiCoUXwUQiNBIXCpQ81IiGfujNmKgWyrQr19WwgDkv3dSfFSDgIbsSEoo03'
SMSIR_LINE_NUMBER = '30007732001185'

# Date formats
fa_formats.DATETIME_FORMAT = "Y/m/d H:i"
fa_formats.DATE_FORMAT = "Y/m/d"

# Persian date settings removed

# CORS settings
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://miepcoj.ir',
    'https://www.miepcoj.ir',
    'https://mtorkzadeh.ir',
    'https://www.mtorkzadeh.ir',
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_CREDENTIALS = True

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SERIALIZER': 'django_redis.serializers.pickle.PickleSerializer',
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            }
        },
        'TIMEOUT': 300,  # 5 minutes
        'KEY_PREFIX': 'hsc_cache',
        'VERSION': 1,
    },
    'sessions': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/2',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SERIALIZER': 'django_redis.serializers.pickle.PickleSerializer',
        },
        'TIMEOUT': 86400,  # 1 day
        'KEY_PREFIX': 'hsc_session',
    },
    'fallback': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'hsc-fallback-cache',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'sessions'
SESSION_COOKIE_AGE = 86400  # 1 day
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF Configuration
CSRF_USE_SESSIONS = False  # استفاده از cookie برای CSRF token
CSRF_COOKIE_HTTPONLY = False  # باید False باشد تا JavaScript بتواند بخواند
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # برای production به True تغییر دهید
CSRF_COOKIE_AGE = 31449600  # 1 year

# Cache middleware settings
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300  # 5 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'hsc_middleware'

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_TIMEZONE = 'Asia/Tehran'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

RUBIKA_BOT = {
    'MAX_USERS_PER_PAGE': 100,
    'CONNECTION_CODE_TTL_MINUTES': 60,
    'LOG_CLEANUP_DAYS': 7,
    'WEBHOOK_RATE_LIMIT': '120/m',
    'WEBHOOK_ALLOWED_IPS': [],
    'BOT_REQUEST_TIMEOUT': 15,
    'DEEPLINK_TEMPLATE': 'https://rubika.ir/{bot_username}?start={code}',
    'PROXY_URL': os.environ.get('RUBIKA_PROXY_URL', ''),
}

if CELERY_AVAILABLE:
    CELERY_BEAT_SCHEDULE = {
        'rubika_bot_cleanup_webhook_logs': {
            'task': 'rubika_bot.tasks.cleanup_webhook_logs',
            'schedule': crontab(hour=3, minute=0),
        },
        'create_scheduled_checklist_instances': {
            'task': 'checklist_app.tasks.create_scheduled_checklist_instances',
            'schedule': crontab(hour=0, minute=0),  # هر روز ساعت 00:00
        },
        # Emergency Services Tasks
        'cleanup_expired_medicines': {
            'task': 'emergency_services.tasks.cleanup_expired_medicines_task',
            'schedule': crontab(hour=2, minute=0),  # هر روز ساعت 2 صبح
            'options': {'expires': 3600}
        },
        'check_medicine_stock_levels': {
            'task': 'emergency_services.tasks.check_medicine_stock_levels_task',
            'schedule': crontab(hour=8, minute=0),  # هر روز ساعت 8 صبح
            'options': {'expires': 3600}
        },
        'mark_expired_medicines_inactive': {
            'task': 'emergency_services.tasks.mark_expired_medicines_inactive_task',
            'schedule': crontab(minute=0),  # هر ساعت
            'options': {'expires': 3600}
        },
        # Corrective Actions Automation Tasks
        'check_unresolved_anomalies': {
            'task': 'corrective_actions.tasks.check_unresolved_anomalies',
            'schedule': crontab(minute=0),  # هر ساعت (برای پردازش تدریجی 5000+ رکورد)
            'options': {'expires': 3600}
        },
        'check_high_risk_assessments': {
            'task': 'corrective_actions.tasks.check_high_risk_assessments',
            'schedule': crontab(hour=7, minute=0),  # هر روز ساعت 7 صبح
            'options': {'expires': 3600}
        },
    }
else:
    CELERY_BEAT_SCHEDULE = {}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'your-email@gmail.com'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}:{lineno} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{asctime}] {levelname} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'json': {
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        # File handlers
        'app_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'application.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 15,  # Keep logs for 15 days
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'filters': ['require_debug_false'],
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'errors.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,  # Keep error logs for 30 days
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'security_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 90,  # Keep security logs for 3 months
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'performance_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'performance.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 7,  # Keep performance logs for 1 week
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Console handler (only in DEBUG mode)
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['require_debug_true'],
        },
        # Mail handler for critical errors (production only)
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'verbose',
            'include_html': False,
        },
    },
    'root': {
        'level': 'INFO',
        'handlers': ['console', 'app_file'],
    },
    'loggers': {
        # Django core loggers
        'django': {
            'handlers': ['console', 'app_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['performance_file'],
            'level': 'WARNING',  # Only log slow queries
            'propagate': False,
        },
        # Application specific loggers
        'accounts': {
            'handlers': ['app_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'BaseInfo': {
            'handlers': ['app_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'OperationsShiftReports': {
            'handlers': ['app_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'meetings': {
            'handlers': ['app_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'contractor_management': {
            'handlers': ['app_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'anomalis': {
            'handlers': ['app_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'hse_incidents': {
            'handlers': ['security_file', 'app_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Cache and performance
        'django_redis': {
            'handlers': ['performance_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'celery': {
            'handlers': ['app_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Third-party loggers (reduce noise)
        'urllib3': {
            'level': 'WARNING',
        },
        'requests': {
            'level': 'WARNING',
        },
    },
}

# Fire Extinguisher Management settings
SMS_ENABLED = True
SMS_PROVIDER = 'smsir'  # Using the existing SMS provider
SMS_API_KEY = SMSIR_API_KEY  # Using the existing API key
SMS_LINE_NUMBER = SMSIR_LINE_NUMBER  # Using the existing line number

# AI Service Configuration
# برای استفاده از OpenAI:
# AI_API_KEY = os.environ.get('AI_API_KEY', '')
# AI_API_BASE_URL = 'https://api.openai.com/v1'
# AI_MODEL = 'gpt-4'  # یا 'gpt-3.5-turbo'
# AI_PROVIDER = 'openai'

# برای استفاده از Anthropic Claude:
# AI_API_KEY = os.environ.get('AI_API_KEY', '')
# AI_API_BASE_URL = 'https://api.anthropic.com/v1'
# AI_MODEL = 'claude-3-opus-20240229'  # یا مدل‌های دیگر
# AI_PROVIDER = 'anthropic'

# برای استفاده از API محلی (مثل Ollama):
# AI_API_KEY = ''  # برای API محلی نیاز نیست
# AI_API_BASE_URL = 'http://localhost:11434/v1'  # آدرس Ollama
# AI_MODEL = 'llama2'  # یا مدل‌های دیگر
# AI_PROVIDER = 'local'

# تنظیمات پیش‌فرض (غیرفعال - باید تنظیم شود)
AI_API_KEY = os.environ.get('AI_API_KEY', '')
AI_API_BASE_URL = os.environ.get('AI_API_BASE_URL', 'https://api.openai.com/v1')
AI_MODEL = os.environ.get('AI_MODEL', 'gpt-4')
AI_PROVIDER = os.environ.get('AI_PROVIDER', 'openai')  # openai, anthropic, local
AI_TIMEOUT = int(os.environ.get('AI_TIMEOUT', '30'))
AI_MAX_RETRIES = int(os.environ.get('AI_MAX_RETRIES', '3'))
AI_CACHE_TIMEOUT = int(os.environ.get('AI_CACHE_TIMEOUT', '3600'))  # 1 hour

# Multi-Provider AI Configuration with Fallback Support
# Google Gemini API Keys (comma-separated for key rotation)
GOOGLE_API_KEYS = [
    key.strip() 
    for key in os.environ.get('GOOGLE_API_KEYS', '').split(',') 
    if key.strip()
]

# Groq API Key (Secondary Provider - Fast Llama 3)
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')

# OpenRouter API Key (Tertiary Provider - Final Fallback)
OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')

# Provider API Base URLs (Default Endpoints)
GOOGLE_API_BASE_URL = os.environ.get('GOOGLE_API_BASE_URL', 'https://generativelanguage.googleapis.com/v1beta')
GROQ_API_BASE_URL = os.environ.get('GROQ_API_BASE_URL', 'https://api.groq.com/openai/v1')
OPENROUTER_API_BASE_URL = os.environ.get('OPENROUTER_API_BASE_URL', 'https://openrouter.ai/api/v1')

# Default Google Model
GOOGLE_DEFAULT_MODEL = os.environ.get('GOOGLE_DEFAULT_MODEL', 'gemini-2.0-flash-lite')

# Groq Model
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'llama3-70b-8192')  # Alternative: 'mixtral-8x7b-32768'

# OpenRouter Model
OPENROUTER_MODEL = os.environ.get('OPENROUTER_MODEL', 'google/gemini-2.0-flash-lite:free')  # Alternative: 'meta-llama/llama-3-8b-instruct' 