# Generated by Django 4.2 on 2025-12-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hse_incidents', '0012_alter_incidentreport_incident_type_and_more'),
        ('risk_assessment', '0005_riskassessment_approval_status_and_more'),
        ('accounts', '0014_userprofile_national_code_alter_payslip_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=100, unique=True, verbose_name='شماره اقدام')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('action_type', models.CharField(choices=[('correction', 'اصلاح'), ('corrective', 'اصلاحی'), ('preventive', 'پیشگیرانه'), ('improvement', 'توصیه بهبود')], max_length=20, verbose_name='نوع اقدام')),
                ('topic', models.CharField(choices=[('quality', 'کیفیت'), ('hse', 'ایمنی، بهداشت و محیط زیست')], max_length=20, verbose_name='موضوع')),
                ('source', models.CharField(choices=[('audit', 'ممیزی داخلی/خارجی'), ('incident', 'رویدادها و حوادث'), ('risk', 'ریسک\u200cها و فرصت\u200cها'), ('inspection', 'بازرسی'), ('feedback', 'شکایات/بازخورد'), ('other', 'سایر')], max_length=20, verbose_name='ورودی عدم انطباق')),
                ('description', models.TextField(verbose_name='شرح عدم انطباق')),
                ('root_cause_analysis', models.TextField(blank=True, null=True, verbose_name='علل ریشه\u200cای عدم انطباق')),
                ('effectiveness_result', models.BooleanField(blank=True, help_text='True = موثر، False = غیرموثر', null=True, verbose_name='نتیجه اثربخشی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('open', 'در حال اجرا'), ('review', 'بررسی اثربخشی'), ('closed', 'بسته شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('created_at_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_corrective_actions', to='accounts.userprofile', verbose_name='پذیرنده / مسئول رسیدگی')),
                ('related_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='hse_incidents.incidentreport', verbose_name='رویداد مرتبط')),
                ('related_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='risk_assessment.riskassessment', verbose_name='ریسک مرتبط')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_corrective_actions', to='accounts.userprofile', verbose_name='درخواست کننده')),
            ],
            options={
                'verbose_name': 'اقدام اصلاحی/پیشگیرانه',
                'verbose_name_plural': 'اقدامات اصلاحی/پیشگیرانه',
                'ordering': ['-created_at', '-created_at_time'],
            },
        ),
        migrations.CreateModel(
            name='SideEffectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.CharField(max_length=255, verbose_name='خطر / جنبه')),
                ('event', models.CharField(max_length=255, verbose_name='رویداد')),
                ('consequence', models.CharField(max_length=500, verbose_name='پیامد')),
                ('control_measure', models.CharField(max_length=500, verbose_name='اقدام کنترلی پیشنهادی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('corrective_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_risks', to='corrective_actions.correctiveaction', verbose_name='اقدام اصلاحی/پیشگیرانه')),
            ],
            options={
                'verbose_name': 'ریسک ناشی از اقدام',
                'verbose_name_plural': 'ریسک\u200cهای ناشی از اقدام',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='شرح اقدام')),
                ('deadline', models.DateField(verbose_name='مهلت اقدام')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انجام')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی')),
                ('corrective_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_steps', to='corrective_actions.correctiveaction', verbose_name='اقدام اصلاحی/پیشگیرانه')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_steps', to='accounts.userprofile', verbose_name='متولی اجرا')),
            ],
            options={
                'verbose_name': 'مرحله اقدام',
                'verbose_name_plural': 'مراحل اقدام',
                'ordering': ['deadline', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['tracking_code'], name='corrective__trackin_84b4e2_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['status'], name='corrective__status_840cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['created_at'], name='corrective__created_c7c664_idx'),
        ),
    ]
