# Generated by Django 4.2 on 2025-12-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anomalis', '0006_comment_file_alter_comment_comment'),
        ('corrective_actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='related_anomaly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='anomalis.anomaly', verbose_name='آنومالی مرتبط'),
        ),
    ]
